export interface CategoryMap {
  domain: string;
  subdomain: string;
}

export const CATEGORY_MAPPING: Record<string, CategoryMap> = {
  // Technology
  'Web Development': { domain: 'Technology', subdomain: 'Web Development' },
  'Full Stack Development': { domain: 'Technology', subdomain: 'Web Development' },
  'Mobile Development': { domain: 'Technology', subdomain: 'Mobile Development' },
  'JavaScript': { domain: 'Technology', subdomain: 'Programming' },
  'Python': { domain: 'Technology', subdomain: 'Programming' },
  'Programming': { domain: 'Technology', subdomain: 'Programming' },
  'Development': { domain: 'Technology', subdomain: 'Programming' },
  'Computer Applications': { domain: 'Technology', subdomain: 'Computer Science' },
  'Computer Science': { domain: 'Technology', subdomain: 'Computer Science' },
  'DSA': { domain: 'Technology', subdomain: 'Computer Science' },
  'System Design': { domain: 'Technology', subdomain: 'Computer Science' },
  'Game Development': { domain: 'Technology', subdomain: 'Game Development' },
  'Blockchain': { domain: 'Technology', subdomain: 'Blockchain' },
  'Cloud Computing': { domain: 'Technology', subdomain: 'Cloud & Infrastructure' },
  'AWS': { domain: 'Technology', subdomain: 'Cloud & Infrastructure' },
  'DevOps': { domain: 'Technology', subdomain: 'Cloud & Infrastructure' },
  'Networking': { domain: 'Technology', subdomain: 'Cloud & Infrastructure' },
  'Cybersecurity': { domain: 'Technology', subdomain: 'Cybersecurity' },
  'Database': { domain: 'Technology', subdomain: 'Database' },

  // AI & Data
  'Machine Learning': { domain: 'AI & Data', subdomain: 'Machine Learning' },
  'AI/ML': { domain: 'AI & Data', subdomain: 'Machine Learning' },
  'Artificial Intelligence': { domain: 'AI & Data', subdomain: 'Artificial Intelligence' },
  'Data Science': { domain: 'AI & Data', subdomain: 'Data Science' },

  // Business & Management
  'Business & Management': { domain: 'Business & Finance', subdomain: 'Management' },
  'Business Administration': { domain: 'Business & Finance', subdomain: 'Management' },
  'Management': { domain: 'Business & Finance', subdomain: 'Management' },
  'Project Management': { domain: 'Business & Finance', subdomain: 'Management' },
  'Business': { domain: 'Business & Finance', subdomain: 'Business' },
  'Supply Chain & Procurement': { domain: 'Business & Finance', subdomain: 'Operations' },
  'Event Management': { domain: 'Business & Finance', subdomain: 'Operations' },
  'Human Resources': { domain: 'Business & Finance', subdomain: 'Human Resources' },
  'Marketing': { domain: 'Business & Finance', subdomain: 'Marketing' },
  'Digital Marketing': { domain: 'Business & Finance', subdomain: 'Marketing' },
  'Content Marketing': { domain: 'Business & Finance', subdomain: 'Marketing' },
  'Social Media Marketing': { domain: 'Business & Finance', subdomain: 'Marketing' },
  'Public Relations & Communications': { domain: 'Business & Finance', subdomain: 'Marketing' },
  'Communication': { domain: 'Business & Finance', subdomain: 'Communication' },
  'Finance': { domain: 'Business & Finance', subdomain: 'Finance' },
  'Finance & Accounting': { domain: 'Business & Finance', subdomain: 'Finance' },
  'Accounting & Finance': { domain: 'Business & Finance', subdomain: 'Finance' },
  'Accounting': { domain: 'Business & Finance', subdomain: 'Finance' },
  'Investment': { domain: 'Business & Finance', subdomain: 'Finance' },
  'Finance & Investment': { domain: 'Business & Finance', subdomain: 'Finance' },
  'Financial Planning': { domain: 'Business & Finance', subdomain: 'Finance' },
  'Economics': { domain: 'Business & Finance', subdomain: 'Economics' },

  // Design & Arts
  'Design': { domain: 'Design & Arts', subdomain: 'Design' },
  'UI/UX Design': { domain: 'Design & Arts', subdomain: 'Design' },
  'Graphic Design': { domain: 'Design & Arts', subdomain: 'Design' },
  'Interior Design': { domain: 'Design & Arts', subdomain: 'Design' },
  'Fashion Design': { domain: 'Design & Arts', subdomain: 'Fashion' },
  'Fashion Styling': { domain: 'Design & Arts', subdomain: 'Fashion' },
  'Architecture': { domain: 'Design & Arts', subdomain: 'Architecture' },
  'Fine Arts': { domain: 'Design & Arts', subdomain: 'Arts' },
  'Arts & Painting': { domain: 'Design & Arts', subdomain: 'Arts' },
  'Music': { domain: 'Design & Arts', subdomain: 'Music' },
  'Performing Arts': { domain: 'Design & Arts', subdomain: 'Performing Arts' },
  'Dance': { domain: 'Design & Arts', subdomain: 'Performing Arts' },
  'Film & Cinema': { domain: 'Design & Arts', subdomain: 'Film & Animation' },
  'Film & Video': { domain: 'Design & Arts', subdomain: 'Film & Animation' },
  'Animation': { domain: 'Design & Arts', subdomain: 'Film & Animation' },
  'Animation & VFX': { domain: 'Design & Arts', subdomain: 'Film & Animation' },
  'Photography': { domain: 'Design & Arts', subdomain: 'Photography' },

  // Humanities & Social Sciences
  'Psychology': { domain: 'Humanities & Social Sciences', subdomain: 'Psychology' },
  'Journalism & Media': { domain: 'Humanities & Social Sciences', subdomain: 'Journalism' },
  'Journalism': { domain: 'Humanities & Social Sciences', subdomain: 'Journalism' },
  'Creative Writing': { domain: 'Humanities & Social Sciences', subdomain: 'Writing' },
  'International Relations': { domain: 'Humanities & Social Sciences', subdomain: 'Political Science' },
  'Political Science': { domain: 'Humanities & Social Sciences', subdomain: 'Political Science' },
  'Social Work': { domain: 'Humanities & Social Sciences', subdomain: 'Sociology' },
  'Museum & Heritage Studies': { domain: 'Humanities & Social Sciences', subdomain: 'History' },
  'Philosophy': { domain: 'Humanities & Social Sciences', subdomain: 'Philosophy' },
  'Law': { domain: 'Humanities & Social Sciences', subdomain: 'Law' },
  'Law & Legal Studies': { domain: 'Humanities & Social Sciences', subdomain: 'Law' },
  'Education': { domain: 'Humanities & Social Sciences', subdomain: 'Education' },
  'Education & Teaching': { domain: 'Humanities & Social Sciences', subdomain: 'Education' },

  // Health & Lifestyle
  'Health & Fitness': { domain: 'Health & Lifestyle', subdomain: 'Health' },
  'Nutrition & Health': { domain: 'Health & Lifestyle', subdomain: 'Nutrition' },
  'Culinary Arts': { domain: 'Health & Lifestyle', subdomain: 'Food & Beverage' },
  'Hospitality & Food & Beverage': { domain: 'Health & Lifestyle', subdomain: 'Food & Beverage' },
  'Environmental Science': { domain: 'Health & Lifestyle', subdomain: 'Environment' },

  // Academics & Exams
  'GRE': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'Exam Prep - GRE': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'CAT': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'Exam Prep - CAT': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'GATE': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'Exam Prep - GATE': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'UPSC': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'Exam Prep - UPSC': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'NEET': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'Exam Prep - NEET': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'JEE': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'Exam Prep - JEE': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'TOEFL': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'IELTS': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'SAT': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'LSAT': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'GMAT': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'MCAT': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },
  'CompTIA': { domain: 'Academics & Exams', subdomain: 'Exam Prep' },

  // Miscellaneous
  'General': { domain: 'General', subdomain: 'General' },
};
