
-- ==================== JavaScript Domain (10 new) ====================
INSERT INTO resources (title, description, link, category, difficulty, is_free, resource_type, section_type, provider, duration, is_active, is_featured, related_skills, education_levels) VALUES
('JavaScript.info - Modern JavaScript', 'The most comprehensive and up-to-date JavaScript tutorial from basics to advanced', 'https://javascript.info/', 'JavaScript', 'beginner', true, 'website', 'domain', 'JavaScript.info', '80 hours', true, true, ARRAY['JavaScript','ES6+','async','closures'], ARRAY['high-school','bachelors']),
('Node.js Complete Developer Course', 'Build REST APIs, GraphQL, real-time apps with Node.js, Express, and MongoDB', 'https://www.udemy.com/course/the-complete-nodejs-developer-course/', 'JavaScript', 'intermediate', false, 'course', 'domain', 'Udemy', '35 hours', true, true, ARRAY['Node.js','Express','MongoDB','REST API'], ARRAY['bachelors']),
('React - The Complete Guide', 'Master React 18+ including hooks, Redux, Next.js, and React Router', 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/', 'JavaScript', 'intermediate', false, 'course', 'domain', 'Udemy', '68 hours', true, true, ARRAY['React','hooks','Redux','Next.js'], ARRAY['bachelors']),
('TypeScript Deep Dive', 'Free online book covering TypeScript from basics to advanced type system features', 'https://basarat.gitbook.io/typescript/', 'JavaScript', 'intermediate', true, 'book', 'domain', 'Basarat Ali Syed', '30 hours', true, false, ARRAY['TypeScript','type system','generics','decorators'], ARRAY['bachelors']),
('JavaScript Algorithms & Data Structures', 'freeCodeCamp certification covering ES6, regex, debugging, OOP, and functional programming', 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/', 'JavaScript', 'beginner', true, 'certification', 'domain', 'freeCodeCamp', '300 hours', true, false, ARRAY['algorithms','data structures','OOP','functional programming'], ARRAY['high-school','bachelors']),
('Vue.js 3 Masterclass', 'Build production-ready apps with Vue 3, Composition API, Pinia, and Vue Router', 'https://www.udemy.com/course/vuejs-2-the-complete-guide/', 'JavaScript', 'intermediate', false, 'course', 'domain', 'Udemy', '32 hours', true, false, ARRAY['Vue.js','Composition API','Pinia'], ARRAY['bachelors']),
('JavaScript Design Patterns', 'Learn creational, structural, and behavioral patterns in JavaScript with real examples', 'https://www.patterns.dev/', 'JavaScript', 'advanced', true, 'book', 'domain', 'Addy Osmani', '15 hours', true, false, ARRAY['design patterns','singleton','observer','factory'], ARRAY['bachelors']),
('Deno & Fresh Framework', 'Modern JavaScript runtime - build web apps with Deno and the Fresh framework', 'https://fresh.deno.dev/', 'JavaScript', 'intermediate', true, 'website', 'domain', 'Deno', '15 hours', true, false, ARRAY['Deno','Fresh','server-side rendering'], ARRAY['bachelors']),
('Testing JavaScript with Jest', 'Complete testing guide covering unit tests, integration tests, and E2E with Cypress', 'https://www.udemy.com/course/javascript-testing-with-jest/', 'JavaScript', 'intermediate', false, 'course', 'domain', 'Udemy', '12 hours', true, false, ARRAY['Jest','testing','Cypress','TDD'], ARRAY['bachelors']),
('Svelte & SvelteKit Complete Course', 'Build reactive web apps with Svelte and full-stack apps with SvelteKit', 'https://www.udemy.com/course/sveltejs-the-complete-guide/', 'JavaScript', 'intermediate', false, 'course', 'domain', 'Udemy', '20 hours', true, false, ARRAY['Svelte','SvelteKit','reactive programming'], ARRAY['bachelors']),

-- ==================== Database Domain (10 new) ====================
('SQL Complete Bootcamp', 'Master SQL from scratch - SELECT, JOINs, subqueries, window functions, and optimization', 'https://www.udemy.com/course/the-complete-sql-bootcamp/', 'Database', 'beginner', false, 'course', 'domain', 'Udemy', '18 hours', true, true, ARRAY['SQL','JOINs','window functions','optimization'], ARRAY['bachelors']),
('MongoDB University - M001 Basics', 'Official MongoDB course on CRUD operations, aggregation, and indexing', 'https://university.mongodb.com/courses/M001/about', 'Database', 'beginner', true, 'certification', 'domain', 'MongoDB University', '15 hours', true, true, ARRAY['MongoDB','NoSQL','aggregation','indexing'], ARRAY['bachelors']),
('PostgreSQL Complete Tutorial', 'Master PostgreSQL including advanced queries, PL/pgSQL, triggers, and performance tuning', 'https://www.udemy.com/course/postgresql-tutorial/', 'Database', 'intermediate', false, 'course', 'domain', 'Udemy', '20 hours', true, false, ARRAY['PostgreSQL','PL/pgSQL','triggers','performance'], ARRAY['bachelors']),
('Redis University', 'Official Redis courses on caching, data structures, and real-time applications', 'https://university.redis.com/', 'Database', 'intermediate', true, 'course', 'domain', 'Redis', '20 hours', true, false, ARRAY['Redis','caching','in-memory','pub/sub'], ARRAY['bachelors']),
('Database Design & Normalization', 'Learn ER diagrams, normalization forms (1NF-5NF), and relational database design', 'https://www.coursera.org/learn/database-management', 'Database', 'intermediate', true, 'course', 'domain', 'Coursera / CU', '24 hours', true, false, ARRAY['database design','normalization','ER diagrams','relational'], ARRAY['bachelors']),
('Neo4j Graph Database Fundamentals', 'Learn graph databases, Cypher query language, and graph data modeling', 'https://graphacademy.neo4j.com/', 'Database', 'intermediate', true, 'certification', 'domain', 'Neo4j', '15 hours', true, false, ARRAY['Neo4j','graph database','Cypher','data modeling'], ARRAY['bachelors']),
('Apache Cassandra for Developers', 'Distributed NoSQL database design, CQL, and data modeling for scalable applications', 'https://www.datastax.com/dev/academy', 'Database', 'advanced', true, 'course', 'domain', 'DataStax', '20 hours', true, false, ARRAY['Cassandra','distributed systems','CQL','NoSQL'], ARRAY['bachelors','masters']),
('Elasticsearch Complete Guide', 'Full-text search, aggregations, and analytics with Elasticsearch and Kibana', 'https://www.udemy.com/course/elasticsearch-complete-guide/', 'Database', 'intermediate', false, 'course', 'domain', 'Udemy', '15 hours', true, false, ARRAY['Elasticsearch','full-text search','Kibana','analytics'], ARRAY['bachelors']),
('Database Performance Optimization', 'Query optimization, indexing strategies, execution plans, and database monitoring', 'https://www.udemy.com/course/sql-performance-tuning/', 'Database', 'advanced', false, 'course', 'domain', 'Udemy', '12 hours', true, false, ARRAY['optimization','indexing','execution plans','monitoring'], ARRAY['bachelors','masters']),
('Supabase Complete Course', 'Build full-stack apps with Supabase - Postgres, Auth, Storage, Edge Functions, and Realtime', 'https://www.udemy.com/course/supabase-course/', 'Database', 'intermediate', false, 'course', 'domain', 'Udemy', '16 hours', true, false, ARRAY['Supabase','Postgres','Auth','Realtime'], ARRAY['bachelors']),

-- ==================== System Design (10 new) ====================
('System Design Interview - Alex Xu', 'The definitive system design interview book covering 16 common system design problems', 'https://www.amazon.com/System-Design-Interview-insiders-Second/dp/B08CMF2CQF', 'System Design', 'intermediate', false, 'book', 'domain', 'Alex Xu', '30 hours', true, true, ARRAY['system design','scalability','distributed systems'], ARRAY['bachelors','masters']),
('Grokking System Design', 'Interactive system design course with visual explanations and practice problems', 'https://www.designgurus.io/course/grokking-the-system-design-interview', 'System Design', 'intermediate', false, 'course', 'domain', 'Design Gurus', '40 hours', true, true, ARRAY['system design','architecture','interviews'], ARRAY['bachelors']),
('MIT Distributed Systems (6.824)', 'MIT''s legendary distributed systems course covering Raft, MapReduce, and fault tolerance', 'https://pdos.csail.mit.edu/6.824/', 'System Design', 'advanced', true, 'course', 'domain', 'MIT', '60 hours', true, true, ARRAY['distributed systems','Raft','MapReduce','fault tolerance'], ARRAY['bachelors','masters']),
('Designing Data-Intensive Applications', 'Martin Kleppmann''s essential book on distributed data systems, replication, and partitioning', 'https://dataintensive.net/', 'System Design', 'advanced', false, 'book', 'domain', 'Martin Kleppmann', '40 hours', true, true, ARRAY['data systems','replication','partitioning','consistency'], ARRAY['masters']),
('High Scalability Blog', 'Real-world architecture case studies of Netflix, Instagram, Uber, and more', 'http://highscalability.com/', 'System Design', 'intermediate', true, 'blog', 'domain', 'High Scalability', '20 hours', true, false, ARRAY['scalability','case studies','architecture patterns'], ARRAY['bachelors','masters']),
('Microservices Architecture', 'Design and build microservices with API gateways, service mesh, and event-driven architecture', 'https://www.udemy.com/course/microservices-architecture/', 'System Design', 'advanced', false, 'course', 'domain', 'Udemy', '25 hours', true, false, ARRAY['microservices','API gateway','service mesh','events'], ARRAY['bachelors','masters']),
('Load Balancing & Caching Patterns', 'Deep dive into load balancing algorithms, CDN caching, and cache invalidation strategies', 'https://www.udemy.com/course/system-design-load-balancing/', 'System Design', 'intermediate', false, 'course', 'domain', 'Udemy', '10 hours', true, false, ARRAY['load balancing','caching','CDN','scalability'], ARRAY['bachelors']),
('Database Sharding & Replication', 'Master horizontal scaling with database sharding, replication topologies, and consistency models', 'https://www.udemy.com/course/database-sharding/', 'System Design', 'advanced', false, 'course', 'domain', 'Udemy', '12 hours', true, false, ARRAY['sharding','replication','consistency','horizontal scaling'], ARRAY['bachelors','masters']),
('Message Queues - Kafka & RabbitMQ', 'Event-driven architecture with Apache Kafka, RabbitMQ, and message queue patterns', 'https://www.udemy.com/course/apache-kafka/', 'System Design', 'intermediate', false, 'course', 'domain', 'Udemy', '18 hours', true, false, ARRAY['Kafka','RabbitMQ','event-driven','message queues'], ARRAY['bachelors']),
('System Design Primer - GitHub', 'Open-source comprehensive guide to system design with visual diagrams and examples', 'https://github.com/donnemartin/system-design-primer', 'System Design', 'intermediate', true, 'website', 'domain', 'GitHub', '30 hours', true, true, ARRAY['system design','architecture','scalability','interviews'], ARRAY['bachelors','masters']),

-- ==================== DSA (10 new) ====================
('NeetCode 150', 'Curated 150 LeetCode problems covering all essential DSA patterns for interviews', 'https://neetcode.io/practice', 'DSA', 'intermediate', true, 'website', 'domain', 'NeetCode', '100 hours', true, true, ARRAY['algorithms','data structures','interview prep','LeetCode'], ARRAY['bachelors']),
('Striver A2Z DSA Sheet', 'Complete DSA roadmap with 450+ problems organized by topic and difficulty', 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/', 'DSA', 'intermediate', true, 'website', 'domain', 'Take U Forward', '200 hours', true, true, ARRAY['DSA','arrays','trees','graphs','dynamic programming'], ARRAY['bachelors']),
('Introduction to Algorithms - MIT OCW', 'MIT''s legendary algorithms course (6.006) covering sorting, graphs, and dynamic programming', 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/', 'DSA', 'intermediate', true, 'course', 'domain', 'MIT OCW', '50 hours', true, true, ARRAY['algorithms','sorting','graphs','dynamic programming'], ARRAY['bachelors']),
('Competitive Programming Handbook', 'Comprehensive guide to competitive programming techniques and contest strategies', 'https://cses.fi/book/book.pdf', 'DSA', 'advanced', true, 'book', 'domain', 'Antti Laaksonen', '30 hours', true, false, ARRAY['competitive programming','algorithms','contests'], ARRAY['bachelors']),
('Graph Algorithms - William Fiset', 'Complete graph theory course covering BFS, DFS, shortest paths, MST, and network flow', 'https://www.youtube.com/playlist?list=PLDV1Zeh2NRsDGO4--qE8yH72HFL1Km93P', 'DSA', 'intermediate', true, 'video', 'domain', 'YouTube', '20 hours', true, false, ARRAY['graph theory','BFS','DFS','shortest paths','MST'], ARRAY['bachelors']),
('Dynamic Programming Patterns', 'Master DP with 50+ problems covering knapsack, LCS, LIS, and interval scheduling', 'https://www.udemy.com/course/dynamic-programming-patterns/', 'DSA', 'advanced', false, 'course', 'domain', 'Udemy', '15 hours', true, false, ARRAY['dynamic programming','knapsack','LCS','memoization'], ARRAY['bachelors']),
('LeetCode Premium - Interview Prep', 'Company-specific interview problems with solutions and discussion from top companies', 'https://leetcode.com/subscribe/', 'DSA', 'intermediate', false, 'website', 'domain', 'LeetCode', '200 hours', true, false, ARRAY['LeetCode','interview prep','company questions'], ARRAY['bachelors']),
('Recursion & Backtracking Masterclass', 'Deep dive into recursion patterns, backtracking, and divide & conquer strategies', 'https://www.udemy.com/course/recursion-backtracking/', 'DSA', 'intermediate', false, 'course', 'domain', 'Udemy', '12 hours', true, false, ARRAY['recursion','backtracking','divide and conquer'], ARRAY['bachelors']),
('Trees & Binary Search Trees', 'Complete guide to tree data structures including BST, AVL, Red-Black, and Trie', 'https://www.udemy.com/course/trees-and-graphs/', 'DSA', 'intermediate', false, 'course', 'domain', 'Udemy', '10 hours', true, false, ARRAY['trees','BST','AVL','Trie','Red-Black tree'], ARRAY['bachelors']),
('Codeforces Problem Set', 'World''s largest competitive programming platform with rated contests and editorials', 'https://codeforces.com/problemset', 'DSA', 'advanced', true, 'website', 'domain', 'Codeforces', '500 hours', true, false, ARRAY['competitive programming','contests','problem solving'], ARRAY['bachelors']),

-- ==================== Design / UI/UX (10 new) ====================
('Google UX Design Certificate', 'Professional certificate covering UX research, wireframing, prototyping, and usability testing', 'https://www.coursera.org/professional-certificates/google-ux-design', 'Design', 'beginner', true, 'certification', 'domain', 'Coursera / Google', '6 months', true, true, ARRAY['UX design','wireframing','prototyping','usability testing'], ARRAY['bachelors']),
('Figma UI Design Masterclass', 'Complete Figma course from basics to advanced - auto layout, components, and design systems', 'https://www.udemy.com/course/figma-ui-ux-design/', 'Design', 'beginner', false, 'course', 'domain', 'Udemy', '20 hours', true, true, ARRAY['Figma','UI design','components','auto layout'], ARRAY['bachelors']),
('Interaction Design Foundation', 'World''s largest online design school with courses on UX, UI, IxD, and design thinking', 'https://www.interaction-design.org/', 'Design', 'intermediate', false, 'learning_path', 'domain', 'IxDF', '200 hours', true, false, ARRAY['interaction design','UX','design thinking','IxD'], ARRAY['bachelors','masters']),
('Laws of UX - Design Principles', 'Collection of essential UX design principles backed by psychology research', 'https://lawsofux.com/', 'Design', 'beginner', true, 'website', 'domain', 'Jon Yablonski', '5 hours', true, false, ARRAY['UX principles','psychology','heuristics','design laws'], ARRAY['bachelors']),
('Design Systems with Figma', 'Build scalable design systems including tokens, components, and documentation', 'https://www.udemy.com/course/design-systems-figma/', 'Design', 'advanced', false, 'course', 'domain', 'Udemy', '15 hours', true, false, ARRAY['design systems','tokens','components','documentation'], ARRAY['bachelors']),
('Adobe XD Essential Training', 'Learn Adobe XD for UI/UX design including prototyping, animations, and responsive design', 'https://www.linkedin.com/learning/adobe-xd-essential-training', 'Design', 'beginner', false, 'course', 'domain', 'LinkedIn Learning', '8 hours', true, false, ARRAY['Adobe XD','prototyping','animations','responsive'], ARRAY['bachelors']),
('User Research Methods', 'Comprehensive guide to user interviews, surveys, usability testing, and card sorting', 'https://www.coursera.org/learn/user-research', 'Design', 'intermediate', true, 'course', 'domain', 'Coursera / Michigan', '15 hours', true, false, ARRAY['user research','interviews','usability testing','surveys'], ARRAY['bachelors']),
('Color Theory for Designers', 'Master color psychology, harmony, accessibility, and color system creation', 'https://www.udemy.com/course/color-theory-for-designers/', 'Design', 'beginner', false, 'course', 'domain', 'Udemy', '6 hours', true, false, ARRAY['color theory','psychology','accessibility','harmony'], ARRAY['bachelors']),
('Typography Fundamentals', 'Learn type selection, pairing, hierarchy, and responsive typography for digital products', 'https://www.udemy.com/course/typography-fundamentals/', 'Design', 'beginner', false, 'course', 'domain', 'Udemy', '5 hours', true, false, ARRAY['typography','type pairing','hierarchy','readability'], ARRAY['bachelors']),
('Motion Design with After Effects', 'Create stunning UI animations and motion graphics for digital products', 'https://www.udemy.com/course/after-effects-motion-design/', 'Design', 'intermediate', false, 'course', 'domain', 'Udemy', '25 hours', true, false, ARRAY['motion design','After Effects','UI animation','motion graphics'], ARRAY['bachelors']);
