
-- =====================================================
-- COMPREHENSIVE SEED DATA: Resources for All Domains & Exams
-- Plus diverse posts for new users
-- =====================================================

-- WEB DEVELOPMENT RESOURCES (12)
INSERT INTO resources (title, description, link, category, difficulty, is_free, icon, color, resource_type, section_type, provider, duration, related_skills, relevant_backgrounds, avg_rating, weighted_rating, total_ratings, recommend_percent, total_votes) VALUES
('The Odin Project', 'Free full-stack curriculum covering HTML, CSS, JavaScript, Node.js, and React with hands-on projects', 'https://www.theodinproject.com', 'Web Development', 'beginner', true, '📚', 'blue', 'course', 'domain', 'The Odin Project', '6 months', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'], ARRAY['Student', 'Career Changer'], 4.9, 4.85, 2450, 98, 2100),
('freeCodeCamp Full Stack', 'Comprehensive web development certification with 300+ hours of free content', 'https://www.freecodecamp.org', 'Web Development', 'beginner', true, '💻', 'green', 'course', 'domain', 'freeCodeCamp', '300 hours', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'], ARRAY['Student', 'Beginner'], 4.8, 4.75, 5200, 96, 4800),
('MDN Web Docs', 'Official Mozilla documentation for web technologies - the gold standard reference', 'https://developer.mozilla.org', 'Web Development', 'intermediate', true, '📖', 'orange', 'website', 'domain', 'Mozilla', 'Self-paced', ARRAY['HTML', 'CSS', 'JavaScript', 'Web APIs'], ARRAY['Developer'], 4.9, 4.88, 8900, 99, 8500),
('JavaScript.info', 'Modern JavaScript tutorial from basics to advanced concepts', 'https://javascript.info', 'Web Development', 'beginner', true, '📗', 'yellow', 'website', 'domain', 'JavaScript.info', 'Self-paced', ARRAY['JavaScript', 'ES6', 'DOM'], ARRAY['Student', 'Developer'], 4.85, 4.80, 3200, 97, 2900),
('CSS-Tricks', 'Tips, tricks, and techniques for modern CSS development', 'https://css-tricks.com', 'Web Development', 'intermediate', true, '🎨', 'pink', 'blog', 'domain', 'CSS-Tricks', 'Self-paced', ARRAY['CSS', 'Flexbox', 'Grid', 'Animations'], ARRAY['Developer', 'Designer'], 4.7, 4.65, 2100, 94, 1900),
('React Official Docs', 'Official React documentation with interactive examples and tutorials', 'https://react.dev', 'Web Development', 'intermediate', true, '⚛️', 'cyan', 'website', 'domain', 'Meta', 'Self-paced', ARRAY['React', 'JavaScript', 'Hooks'], ARRAY['Developer'], 4.9, 4.87, 6500, 98, 6200),
('Next.js Learn', 'Interactive Next.js course by Vercel - build full-stack apps', 'https://nextjs.org/learn', 'Web Development', 'intermediate', true, '▲', 'black', 'course', 'domain', 'Vercel', '16 hours', ARRAY['Next.js', 'React', 'SSR', 'APIs'], ARRAY['Developer'], 4.85, 4.80, 1800, 97, 1650),
('Tailwind CSS Docs', 'Utility-first CSS framework - comprehensive documentation', 'https://tailwindcss.com/docs', 'Web Development', 'beginner', true, '🌊', 'teal', 'website', 'domain', 'Tailwind Labs', 'Self-paced', ARRAY['CSS', 'Tailwind', 'Responsive Design'], ARRAY['Developer', 'Designer'], 4.9, 4.86, 4200, 98, 4000),
('Web Dev Simplified', 'YouTube channel with practical web development tutorials', 'https://www.youtube.com/@WebDevSimplified', 'Web Development', 'beginner', true, '🎬', 'red', 'video', 'domain', 'Kyle Cook', 'Self-paced', ARRAY['JavaScript', 'React', 'CSS'], ARRAY['Student', 'Beginner'], 4.8, 4.76, 3600, 96, 3400),
('Eloquent JavaScript', 'Free online book on JavaScript programming', 'https://eloquentjavascript.net', 'Web Development', 'intermediate', true, '📕', 'brown', 'book', 'domain', 'Marijn Haverbeke', '20 hours', ARRAY['JavaScript', 'Programming', 'DOM'], ARRAY['Student', 'Developer'], 4.7, 4.65, 2400, 93, 2200),
('Frontend Masters', 'Expert-led video courses on frontend technologies', 'https://frontendmasters.com', 'Web Development', 'intermediate', false, '🎓', 'red', 'course', 'domain', 'Frontend Masters', 'Self-paced', ARRAY['JavaScript', 'TypeScript', 'React', 'Node.js'], ARRAY['Developer'], 4.85, 4.80, 2800, 97, 2600),
('Scrimba Frontend Path', 'Interactive coding platform for frontend development', 'https://scrimba.com/learn/frontend', 'Web Development', 'beginner', false, '🎓', 'purple', 'course', 'domain', 'Scrimba', '70 hours', ARRAY['HTML', 'CSS', 'JavaScript', 'React'], ARRAY['Student', 'Career Changer'], 4.75, 4.70, 1500, 95, 1400),

-- DATA SCIENCE RESOURCES (12)
('Kaggle Learn', 'Free micro-courses on data science and machine learning', 'https://www.kaggle.com/learn', 'Data Science', 'beginner', true, '📊', 'blue', 'course', 'domain', 'Kaggle', '40 hours', ARRAY['Python', 'Pandas', 'Machine Learning'], ARRAY['Student', 'Analyst'], 4.85, 4.80, 4500, 97, 4200),
('Python for Data Analysis', 'Essential book by Wes McKinney on pandas and data wrangling', 'https://wesmckinney.com/book/', 'Data Science', 'intermediate', true, '📘', 'yellow', 'book', 'domain', 'Wes McKinney', '15 hours', ARRAY['Python', 'Pandas', 'NumPy'], ARRAY['Student', 'Analyst'], 4.8, 4.75, 3200, 96, 2900),
('StatQuest with Josh Starmer', 'YouTube channel explaining statistics and ML clearly', 'https://www.youtube.com/@statquest', 'Data Science', 'beginner', true, '🎬', 'green', 'video', 'domain', 'Josh Starmer', 'Self-paced', ARRAY['Statistics', 'Machine Learning', 'Deep Learning'], ARRAY['Student', 'Analyst'], 4.9, 4.88, 5600, 99, 5400),
('Coursera Data Science Specialization', 'Johns Hopkins University data science certificate', 'https://www.coursera.org/specializations/jhu-data-science', 'Data Science', 'beginner', false, '🎓', 'blue', 'certification', 'domain', 'Johns Hopkins', '11 months', ARRAY['R', 'Statistics', 'Machine Learning'], ARRAY['Student', 'Analyst'], 4.7, 4.65, 8500, 93, 7800),
('fast.ai Practical Deep Learning', 'Free course making neural networks accessible', 'https://course.fast.ai', 'Data Science', 'intermediate', true, '🧠', 'purple', 'course', 'domain', 'fast.ai', '7 weeks', ARRAY['Deep Learning', 'PyTorch', 'Computer Vision'], ARRAY['Developer', 'Researcher'], 4.9, 4.87, 4200, 98, 4000),
('DataCamp', 'Interactive data science learning platform', 'https://www.datacamp.com', 'Data Science', 'beginner', false, '🐍', 'green', 'course', 'domain', 'DataCamp', 'Self-paced', ARRAY['Python', 'R', 'SQL', 'Pandas'], ARRAY['Student', 'Analyst'], 4.6, 4.55, 6200, 91, 5800),
('Towards Data Science', 'Medium publication for data science articles', 'https://towardsdatascience.com', 'Data Science', 'intermediate', true, '📰', 'black', 'blog', 'domain', 'Medium', 'Self-paced', ARRAY['Machine Learning', 'Python', 'Deep Learning'], ARRAY['Data Scientist'], 4.5, 4.45, 3800, 88, 3500),
('Hands-On Machine Learning', 'Aurélien Géron s essential ML textbook', 'https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125967/', 'Data Science', 'intermediate', false, '📕', 'orange', 'book', 'domain', 'O Reilly', '25 hours', ARRAY['Machine Learning', 'TensorFlow', 'Scikit-learn'], ARRAY['Developer', 'Data Scientist'], 4.85, 4.80, 4800, 97, 4500),
('Google Data Analytics Certificate', 'Professional certificate from Google on Coursera', 'https://www.coursera.org/professional-certificates/google-data-analytics', 'Data Science', 'beginner', false, '🎓', 'blue', 'certification', 'domain', 'Google', '6 months', ARRAY['SQL', 'R', 'Tableau', 'Data Visualization'], ARRAY['Career Changer', 'Student'], 4.7, 4.65, 12000, 93, 11000),
('3Blue1Brown Neural Networks', 'Visual explanations of neural network concepts', 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi', 'Data Science', 'beginner', true, '🎬', 'blue', 'video', 'domain', '3Blue1Brown', '4 hours', ARRAY['Neural Networks', 'Deep Learning', 'Mathematics'], ARRAY['Student', 'Developer'], 4.95, 4.92, 8200, 99, 8000),
('Anaconda Distribution', 'Python data science platform and package manager', 'https://www.anaconda.com/download', 'Data Science', 'beginner', true, '🐍', 'green', 'tool', 'domain', 'Anaconda', 'Self-paced', ARRAY['Python', 'Jupyter', 'Conda'], ARRAY['Student', 'Data Scientist'], 4.7, 4.65, 9500, 94, 9000),
('Scikit-learn Documentation', 'Official docs for Python machine learning library', 'https://scikit-learn.org/stable/', 'Data Science', 'intermediate', true, '📖', 'orange', 'website', 'domain', 'Scikit-learn', 'Self-paced', ARRAY['Machine Learning', 'Python', 'Classification'], ARRAY['Developer', 'Data Scientist'], 4.8, 4.76, 6800, 96, 6500),

-- AI/ML RESOURCES (12)
('Andrew Ng Machine Learning', 'The most famous ML course on Coursera', 'https://www.coursera.org/learn/machine-learning', 'AI/ML', 'beginner', true, '🎓', 'blue', 'course', 'domain', 'Stanford/Coursera', '60 hours', ARRAY['Machine Learning', 'Neural Networks', 'Python'], ARRAY['Student', 'Developer'], 4.9, 4.88, 180000, 98, 175000),
('DeepLearning.AI Specialization', 'Deep learning courses by Andrew Ng', 'https://www.deeplearning.ai/courses/', 'AI/ML', 'intermediate', false, '🧠', 'blue', 'course', 'domain', 'DeepLearning.AI', '5 months', ARRAY['Deep Learning', 'TensorFlow', 'Neural Networks'], ARRAY['Developer', 'Researcher'], 4.85, 4.82, 45000, 97, 43000),
('Hugging Face Course', 'Free NLP course using transformers library', 'https://huggingface.co/course', 'AI/ML', 'intermediate', true, '🤗', 'yellow', 'course', 'domain', 'Hugging Face', '20 hours', ARRAY['NLP', 'Transformers', 'PyTorch'], ARRAY['Developer', 'Researcher'], 4.8, 4.76, 8500, 96, 8200),
('PyTorch Tutorials', 'Official PyTorch learning resources', 'https://pytorch.org/tutorials/', 'AI/ML', 'intermediate', true, '🔥', 'orange', 'website', 'domain', 'PyTorch', 'Self-paced', ARRAY['PyTorch', 'Deep Learning', 'Computer Vision'], ARRAY['Developer', 'Researcher'], 4.85, 4.80, 12000, 97, 11500),
('TensorFlow Developer Certificate', 'Google certification for TensorFlow developers', 'https://www.tensorflow.org/certificate', 'AI/ML', 'intermediate', false, '🎖️', 'orange', 'certification', 'domain', 'Google', '3 months', ARRAY['TensorFlow', 'Deep Learning', 'Python'], ARRAY['Developer'], 4.7, 4.65, 6800, 93, 6400),
('Papers With Code', 'ML papers with implementation code', 'https://paperswithcode.com', 'AI/ML', 'advanced', true, '📄', 'blue', 'website', 'domain', 'Papers With Code', 'Self-paced', ARRAY['Research', 'Deep Learning', 'State of the Art'], ARRAY['Researcher', 'Developer'], 4.9, 4.87, 15000, 98, 14500),
('MIT Introduction to Deep Learning', 'Free MIT course on deep learning fundamentals', 'http://introtodeeplearning.com', 'AI/ML', 'beginner', true, '🎓', 'red', 'course', 'domain', 'MIT', '12 hours', ARRAY['Deep Learning', 'TensorFlow', 'Neural Networks'], ARRAY['Student', 'Developer'], 4.8, 4.76, 9500, 96, 9200),
('Lex Fridman Podcast', 'Podcast interviews with AI researchers', 'https://lexfridman.com/podcast/', 'AI/ML', 'beginner', true, '🎙️', 'black', 'video', 'domain', 'Lex Fridman', 'Self-paced', ARRAY['AI', 'Research', 'Philosophy'], ARRAY['Student', 'Researcher'], 4.85, 4.80, 22000, 97, 21000),
('Neural Networks from Scratch', 'Book teaching neural networks using only NumPy', 'https://nnfs.io', 'AI/ML', 'intermediate', false, '📕', 'purple', 'book', 'domain', 'Harrison Kinsley', '15 hours', ARRAY['Neural Networks', 'Python', 'NumPy'], ARRAY['Developer', 'Student'], 4.75, 4.70, 3200, 95, 3000),
('OpenAI Cookbook', 'Examples and guides for using OpenAI APIs', 'https://cookbook.openai.com', 'AI/ML', 'intermediate', true, '📖', 'green', 'website', 'domain', 'OpenAI', 'Self-paced', ARRAY['GPT', 'APIs', 'Prompt Engineering'], ARRAY['Developer'], 4.8, 4.76, 8900, 96, 8600),
('LangChain Documentation', 'Framework for building LLM applications', 'https://docs.langchain.com', 'AI/ML', 'intermediate', true, '🦜', 'green', 'website', 'domain', 'LangChain', 'Self-paced', ARRAY['LLMs', 'RAG', 'Agents', 'Python'], ARRAY['Developer'], 4.7, 4.65, 5600, 93, 5300),
('Two Minute Papers', 'YouTube channel on latest AI research', 'https://www.youtube.com/@TwoMinutePapers', 'AI/ML', 'beginner', true, '🎬', 'red', 'video', 'domain', 'Károly Zsolnai-Fehér', 'Self-paced', ARRAY['AI Research', 'Computer Graphics', 'Deep Learning'], ARRAY['Student', 'Enthusiast'], 4.85, 4.80, 15000, 97, 14500),

-- CYBERSECURITY RESOURCES (12)
('TryHackMe', 'Interactive cybersecurity training platform', 'https://tryhackme.com', 'Cybersecurity', 'beginner', true, '🔐', 'green', 'course', 'domain', 'TryHackMe', 'Self-paced', ARRAY['Penetration Testing', 'Linux', 'Networking'], ARRAY['Student', 'IT Professional'], 4.9, 4.87, 25000, 98, 24000),
('HackTheBox', 'Hands-on cybersecurity labs and challenges', 'https://www.hackthebox.com', 'Cybersecurity', 'intermediate', true, '💀', 'green', 'course', 'domain', 'Hack The Box', 'Self-paced', ARRAY['Penetration Testing', 'CTF', 'Red Team'], ARRAY['Security Professional'], 4.85, 4.80, 18000, 97, 17500),
('OWASP Top 10', 'Essential web application security risks guide', 'https://owasp.org/www-project-top-ten/', 'Cybersecurity', 'intermediate', true, '📖', 'blue', 'website', 'domain', 'OWASP', '4 hours', ARRAY['Web Security', 'Vulnerabilities', 'AppSec'], ARRAY['Developer', 'Security Professional'], 4.8, 4.76, 12000, 96, 11500),
('CompTIA Security+ Study Guide', 'Preparation resources for Security+ certification', 'https://www.comptia.org/certifications/security', 'Cybersecurity', 'beginner', false, '🎓', 'red', 'certification', 'domain', 'CompTIA', '3 months', ARRAY['Security Fundamentals', 'Networking', 'Risk Management'], ARRAY['IT Professional', 'Career Changer'], 4.7, 4.65, 35000, 94, 33000),
('PortSwigger Web Security Academy', 'Free web security training with labs', 'https://portswigger.net/web-security', 'Cybersecurity', 'intermediate', true, '🌐', 'orange', 'course', 'domain', 'PortSwigger', 'Self-paced', ARRAY['Web Security', 'Burp Suite', 'SQL Injection'], ARRAY['Developer', 'Security Professional'], 4.9, 4.88, 15000, 99, 14800),
('Cybrary', 'Free cybersecurity and IT training platform', 'https://www.cybrary.it', 'Cybersecurity', 'beginner', true, '🎓', 'purple', 'course', 'domain', 'Cybrary', 'Self-paced', ARRAY['Security', 'Networking', 'Ethical Hacking'], ARRAY['Student', 'IT Professional'], 4.5, 4.45, 8500, 89, 8000),
('The Hacker News', 'Cybersecurity news and analysis', 'https://thehackernews.com', 'Cybersecurity', 'beginner', true, '📰', 'black', 'blog', 'domain', 'The Hacker News', 'Daily', ARRAY['Security News', 'Vulnerabilities', 'Threats'], ARRAY['Security Professional'], 4.7, 4.65, 9500, 94, 9000),
('Krebs on Security', 'In-depth cybersecurity investigative journalism', 'https://krebsonsecurity.com', 'Cybersecurity', 'intermediate', true, '📰', 'red', 'blog', 'domain', 'Brian Krebs', 'Weekly', ARRAY['Security Research', 'Cybercrime', 'Investigations'], ARRAY['Security Professional'], 4.85, 4.80, 7500, 97, 7200),
('SANS Cyber Aces', 'Free foundational cybersecurity courses', 'https://www.cyberaces.org', 'Cybersecurity', 'beginner', true, '🎓', 'blue', 'course', 'domain', 'SANS', '20 hours', ARRAY['Networking', 'Operating Systems', 'Security Fundamentals'], ARRAY['Student', 'IT Professional'], 4.6, 4.55, 5500, 91, 5200),
('Offensive Security OSCP', 'Industry-leading penetration testing certification', 'https://www.offensive-security.com/pwk-oscp/', 'Cybersecurity', 'advanced', false, '🏆', 'red', 'certification', 'domain', 'Offensive Security', '3 months', ARRAY['Penetration Testing', 'Exploitation', 'Kali Linux'], ARRAY['Security Professional'], 4.9, 4.87, 12000, 98, 11800),
('VulnHub', 'Free vulnerable VMs for practice', 'https://www.vulnhub.com', 'Cybersecurity', 'intermediate', true, '💻', 'green', 'website', 'domain', 'VulnHub', 'Self-paced', ARRAY['CTF', 'Penetration Testing', 'Linux'], ARRAY['Security Professional'], 4.7, 4.65, 6500, 94, 6200),
('LiveOverflow', 'YouTube channel on hacking and security', 'https://www.youtube.com/@LiveOverflow', 'Cybersecurity', 'intermediate', true, '🎬', 'red', 'video', 'domain', 'LiveOverflow', 'Self-paced', ARRAY['Hacking', 'CTF', 'Binary Exploitation'], ARRAY['Security Professional', 'Student'], 4.85, 4.80, 8500, 97, 8200),

-- CLOUD COMPUTING RESOURCES (12)
('AWS Free Tier & Training', 'Official AWS free tier and training resources', 'https://aws.amazon.com/training/', 'Cloud Computing', 'beginner', true, '☁️', 'orange', 'course', 'domain', 'Amazon', 'Self-paced', ARRAY['AWS', 'EC2', 'S3', 'Lambda'], ARRAY['Developer', 'IT Professional'], 4.8, 4.76, 45000, 96, 43000),
('Google Cloud Skills Boost', 'Free Google Cloud training and labs', 'https://www.cloudskillsboost.google', 'Cloud Computing', 'beginner', true, '🌐', 'blue', 'course', 'domain', 'Google', 'Self-paced', ARRAY['GCP', 'BigQuery', 'Kubernetes'], ARRAY['Developer', 'IT Professional'], 4.75, 4.70, 28000, 95, 26500),
('Microsoft Learn Azure', 'Free Azure learning paths and certifications', 'https://learn.microsoft.com/en-us/azure/', 'Cloud Computing', 'beginner', true, '📘', 'blue', 'course', 'domain', 'Microsoft', 'Self-paced', ARRAY['Azure', 'Cloud', 'DevOps'], ARRAY['Developer', 'IT Professional'], 4.7, 4.65, 35000, 94, 33000),
('A Cloud Guru', 'Cloud certification training platform', 'https://acloudguru.com', 'Cloud Computing', 'beginner', false, '🎓', 'orange', 'course', 'domain', 'A Cloud Guru', 'Self-paced', ARRAY['AWS', 'Azure', 'GCP', 'Certifications'], ARRAY['IT Professional', 'Developer'], 4.7, 4.65, 18000, 93, 17000),
('AWS Solutions Architect Associate', 'Most popular cloud certification', 'https://aws.amazon.com/certification/certified-solutions-architect-associate/', 'Cloud Computing', 'intermediate', false, '🏆', 'orange', 'certification', 'domain', 'Amazon', '3 months', ARRAY['AWS', 'Architecture', 'Cloud Design'], ARRAY['Developer', 'Architect'], 4.85, 4.80, 85000, 97, 82000),
('Terraform Documentation', 'Infrastructure as Code with Terraform', 'https://developer.hashicorp.com/terraform/docs', 'Cloud Computing', 'intermediate', true, '📖', 'purple', 'website', 'domain', 'HashiCorp', 'Self-paced', ARRAY['Terraform', 'IaC', 'Cloud Automation'], ARRAY['DevOps', 'Developer'], 4.8, 4.76, 15000, 96, 14500),
('Kubernetes Documentation', 'Official Kubernetes docs and tutorials', 'https://kubernetes.io/docs/home/', 'Cloud Computing', 'intermediate', true, '⚓', 'blue', 'website', 'domain', 'CNCF', 'Self-paced', ARRAY['Kubernetes', 'Containers', 'Orchestration'], ARRAY['DevOps', 'Developer'], 4.75, 4.70, 25000, 95, 24000),
('Docker Get Started', 'Official Docker getting started guide', 'https://docs.docker.com/get-started/', 'Cloud Computing', 'beginner', true, '🐳', 'blue', 'website', 'domain', 'Docker', '4 hours', ARRAY['Docker', 'Containers', 'Microservices'], ARRAY['Developer', 'DevOps'], 4.8, 4.76, 32000, 96, 31000),
('Cloud Resume Challenge', 'Hands-on cloud project for beginners', 'https://cloudresumechallenge.dev', 'Cloud Computing', 'beginner', true, '🚀', 'yellow', 'course', 'domain', 'Forrest Brazeal', '2 weeks', ARRAY['AWS', 'Azure', 'GCP', 'Serverless'], ARRAY['Career Changer', 'Student'], 4.9, 4.87, 8500, 98, 8300),
('The Cloud Girl YouTube', 'Cloud computing tutorials for beginners', 'https://www.youtube.com/@thecloudgirl', 'Cloud Computing', 'beginner', true, '🎬', 'purple', 'video', 'domain', 'Priyanka Vergadia', 'Self-paced', ARRAY['GCP', 'Cloud Concepts', 'Tutorials'], ARRAY['Student', 'Beginner'], 4.75, 4.70, 5500, 95, 5200),
('Linux Academy', 'Cloud and Linux training platform', 'https://www.pluralsight.com/cloud-guru', 'Cloud Computing', 'intermediate', false, '🐧', 'green', 'course', 'domain', 'Pluralsight', 'Self-paced', ARRAY['Linux', 'AWS', 'DevOps'], ARRAY['IT Professional', 'Developer'], 4.6, 4.55, 12000, 91, 11500),
('Serverless Framework Docs', 'Build serverless applications easily', 'https://www.serverless.com/framework/docs', 'Cloud Computing', 'intermediate', true, '⚡', 'orange', 'website', 'domain', 'Serverless', 'Self-paced', ARRAY['Serverless', 'Lambda', 'AWS'], ARRAY['Developer'], 4.7, 4.65, 8500, 94, 8200),

-- DEVOPS RESOURCES (12)
('DevOps Roadmap', 'Complete DevOps learning path', 'https://roadmap.sh/devops', 'DevOps', 'beginner', true, '🗺️', 'purple', 'website', 'domain', 'roadmap.sh', 'Self-paced', ARRAY['DevOps', 'CI/CD', 'Cloud', 'Linux'], ARRAY['Developer', 'IT Professional'], 4.85, 4.80, 22000, 97, 21500),
('GitHub Actions Documentation', 'CI/CD with GitHub Actions', 'https://docs.github.com/en/actions', 'DevOps', 'beginner', true, '🔄', 'black', 'website', 'domain', 'GitHub', 'Self-paced', ARRAY['CI/CD', 'GitHub Actions', 'Automation'], ARRAY['Developer'], 4.8, 4.76, 18000, 96, 17500),
('Jenkins User Documentation', 'Popular CI/CD server documentation', 'https://www.jenkins.io/doc/', 'DevOps', 'intermediate', true, '🔧', 'red', 'website', 'domain', 'Jenkins', 'Self-paced', ARRAY['Jenkins', 'CI/CD', 'Automation'], ARRAY['DevOps', 'Developer'], 4.6, 4.55, 15000, 91, 14200),
('Ansible Documentation', 'IT automation platform docs', 'https://docs.ansible.com', 'DevOps', 'intermediate', true, '📖', 'red', 'website', 'domain', 'Red Hat', 'Self-paced', ARRAY['Ansible', 'Configuration Management', 'Automation'], ARRAY['DevOps', 'IT Professional'], 4.7, 4.65, 12000, 94, 11500),
('Linux Command Line Basics', 'Linux Foundation free course', 'https://training.linuxfoundation.org/training/linux-command-line-basics/', 'DevOps', 'beginner', true, '🐧', 'black', 'course', 'domain', 'Linux Foundation', '10 hours', ARRAY['Linux', 'Command Line', 'Bash'], ARRAY['Student', 'Developer'], 4.75, 4.70, 25000, 95, 24000),
('Prometheus Documentation', 'Monitoring and alerting toolkit', 'https://prometheus.io/docs/', 'DevOps', 'intermediate', true, '📊', 'orange', 'website', 'domain', 'CNCF', 'Self-paced', ARRAY['Prometheus', 'Monitoring', 'Metrics'], ARRAY['DevOps', 'SRE'], 4.7, 4.65, 8500, 94, 8200),
('Grafana Tutorials', 'Data visualization for monitoring', 'https://grafana.com/tutorials/', 'DevOps', 'intermediate', true, '📈', 'orange', 'website', 'domain', 'Grafana Labs', 'Self-paced', ARRAY['Grafana', 'Dashboards', 'Monitoring'], ARRAY['DevOps', 'SRE'], 4.75, 4.70, 9500, 95, 9200),
('The Phoenix Project', 'DevOps novel teaching key concepts', 'https://www.amazon.com/Phoenix-Project-DevOps-Helping-Business/dp/1942788290', 'DevOps', 'beginner', false, '📕', 'red', 'book', 'domain', 'Gene Kim', '10 hours', ARRAY['DevOps Culture', 'IT Operations', 'Lean'], ARRAY['Manager', 'Developer'], 4.8, 4.76, 35000, 96, 34000),
('Site Reliability Engineering Book', 'Free SRE book from Google', 'https://sre.google/sre-book/table-of-contents/', 'DevOps', 'advanced', true, '📘', 'blue', 'book', 'domain', 'Google', '20 hours', ARRAY['SRE', 'Reliability', 'Operations'], ARRAY['SRE', 'DevOps'], 4.85, 4.80, 18000, 97, 17500),
('TechWorld with Nana', 'DevOps tutorials on YouTube', 'https://www.youtube.com/@TechWorldwithNana', 'DevOps', 'beginner', true, '🎬', 'red', 'video', 'domain', 'Nana Janashia', 'Self-paced', ARRAY['DevOps', 'Kubernetes', 'Docker'], ARRAY['Student', 'Developer'], 4.9, 4.87, 15000, 98, 14800),
('Helm Documentation', 'Kubernetes package manager', 'https://helm.sh/docs/', 'DevOps', 'intermediate', true, '⚓', 'blue', 'website', 'domain', 'CNCF', 'Self-paced', ARRAY['Helm', 'Kubernetes', 'Charts'], ARRAY['DevOps', 'Developer'], 4.65, 4.60, 6500, 93, 6200),
('CircleCI Documentation', 'CI/CD platform documentation', 'https://circleci.com/docs/', 'DevOps', 'intermediate', true, '🔄', 'green', 'website', 'domain', 'CircleCI', 'Self-paced', ARRAY['CI/CD', 'Automation', 'Testing'], ARRAY['Developer', 'DevOps'], 4.6, 4.55, 5500, 91, 5200);
