-- ============================================================
-- ZONE C: ACTIVITY  (event spine)
-- ============================================================

CREATE TYPE public.interaction_subject AS ENUM
  ('resource','post','roadmap','skill','profile','search','user_resource');

CREATE TYPE public.interaction_verb AS ENUM
  ('impression','click','open','dwell','download','like','unlike','save','unsave',
   'share','comment','rate','vote','complete','search');

CREATE TABLE public.interaction_events (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id       uuid NOT NULL,
  session_id    uuid,
  subject_type  public.interaction_subject NOT NULL,
  subject_id    uuid,
  event_type    public.interaction_verb NOT NULL,
  dwell_ms      integer,
  position      integer,
  surface       text,
  variant       text,
  model_version text,
  sequence_no   integer,
  context       jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at   timestamptz NOT NULL DEFAULT now(),
  created_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, occurred_at),
  CONSTRAINT interaction_events_dwell_sane CHECK (dwell_ms IS NULL OR (dwell_ms >= 0 AND dwell_ms <= 1800000))
) PARTITION BY RANGE (occurred_at);

-- history partition (all pre-existing backfilled data) + rolling monthly partitions
CREATE TABLE public.interaction_events_history PARTITION OF public.interaction_events
  FOR VALUES FROM (MINVALUE) TO ('2026-08-01');

DO $$
DECLARE
  m date := date_trunc('month', now())::date;
  i integer;
BEGIN
  FOR i IN 0..14 LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS public.interaction_events_%s PARTITION OF public.interaction_events FOR VALUES FROM (%L) TO (%L)',
      to_char(m + (i || ' month')::interval, 'YYYY_MM'),
      (m + (i || ' month')::interval)::date,
      (m + ((i + 1) || ' month')::interval)::date
    );
  END LOOP;
END $$;

CREATE TABLE public.interaction_events_future PARTITION OF public.interaction_events DEFAULT;

CREATE INDEX idx_ie_user_time    ON public.interaction_events (user_id, occurred_at DESC);
CREATE INDEX idx_ie_subject      ON public.interaction_events (subject_type, subject_id, event_type);
CREATE INDEX idx_ie_session_seq  ON public.interaction_events (session_id, sequence_no);
CREATE INDEX idx_ie_verb_time    ON public.interaction_events (event_type, occurred_at DESC);
CREATE INDEX idx_ie_occurred_brin ON public.interaction_events USING brin (occurred_at);

GRANT SELECT, INSERT ON public.interaction_events TO authenticated;
GRANT ALL ON public.interaction_events TO service_role;
ALTER TABLE public.interaction_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users insert their own events"
  ON public.interaction_events FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users read their own events"
  ON public.interaction_events FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- helper: appends an event and auto-assigns sequence_no within the session
CREATE OR REPLACE FUNCTION public.track_interaction(
  _subject_type public.interaction_subject,
  _event_type   public.interaction_verb,
  _subject_id   uuid DEFAULT NULL,
  _session_id   uuid DEFAULT NULL,
  _surface      text DEFAULT NULL,
  _dwell_ms     integer DEFAULT NULL,
  _position     integer DEFAULT NULL,
  _variant      text DEFAULT NULL,
  _model_version text DEFAULT NULL,
  _context      jsonb DEFAULT '{}'::jsonb
) RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _uid uuid := auth.uid();
  _seq integer;
  _id  bigint;
BEGIN
  IF _uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF _session_id IS NOT NULL THEN
    SELECT COALESCE(MAX(sequence_no), 0) + 1 INTO _seq
    FROM interaction_events
    WHERE session_id = _session_id AND user_id = _uid;
  END IF;

  INSERT INTO interaction_events (
    user_id, session_id, subject_type, subject_id, event_type,
    dwell_ms, position, surface, variant, model_version, sequence_no, context
  ) VALUES (
    _uid, _session_id, _subject_type, _subject_id, _event_type,
    CASE WHEN _dwell_ms IS NULL THEN NULL ELSE LEAST(GREATEST(_dwell_ms, 0), 1800000) END,
    _position, _surface, _variant, _model_version, _seq, COALESCE(_context, '{}'::jsonb)
  ) RETURNING id INTO _id;

  RETURN _id;
END;
$$;

-- ============================================================
-- ZONE C: satellites (state, not events)
-- ============================================================

CREATE TABLE public.saved_items (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL,
  subject_type  public.interaction_subject NOT NULL,
  subject_id    uuid NOT NULL,
  collection_id uuid REFERENCES public.saved_posts_collections(id) ON DELETE SET NULL,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, subject_type, subject_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.saved_items TO authenticated;
GRANT ALL ON public.saved_items TO service_role;
ALTER TABLE public.saved_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own saved items"
  ON public.saved_items FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE INDEX idx_saved_items_user ON public.saved_items (user_id, subject_type, created_at DESC);
CREATE TRIGGER trg_saved_items_updated_at BEFORE UPDATE ON public.saved_items
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.post_engagement (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL,
  post_id    uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, post_id)
);
GRANT SELECT, INSERT, DELETE ON public.post_engagement TO authenticated;
GRANT SELECT ON public.post_engagement TO anon;
GRANT ALL ON public.post_engagement TO service_role;
ALTER TABLE public.post_engagement ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read post engagement"
  ON public.post_engagement FOR SELECT USING (true);
CREATE POLICY "Users add their own engagement"
  ON public.post_engagement FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users remove their own engagement"
  ON public.post_engagement FOR DELETE TO authenticated
  USING (user_id = auth.uid());
CREATE INDEX idx_post_engagement_post ON public.post_engagement (post_id);

-- ============================================================
-- ZONE B: catalog split
-- ============================================================

CREATE TABLE public.resource_stats (
  resource_id       uuid PRIMARY KEY REFERENCES public.resources(id) ON DELETE CASCADE,
  avg_rating        numeric(3,2),
  weighted_rating   numeric(4,2),
  total_ratings     integer NOT NULL DEFAULT 0,
  recommend_percent integer,
  total_votes       integer NOT NULL DEFAULT 0,
  total_reviews     integer NOT NULL DEFAULT 0,
  view_count        integer NOT NULL DEFAULT 0,
  click_count       integer NOT NULL DEFAULT 0,
  total_dwell_ms    bigint  NOT NULL DEFAULT 0,
  updated_at        timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.resource_stats TO anon, authenticated;
GRANT ALL ON public.resource_stats TO service_role;
ALTER TABLE public.resource_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Resource stats are public" ON public.resource_stats FOR SELECT USING (true);
CREATE POLICY "Admins manage resource stats" ON public.resource_stats FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE INDEX idx_resource_stats_weighted ON public.resource_stats (weighted_rating DESC NULLS LAST);

CREATE TABLE public.resource_skills (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id   uuid NOT NULL REFERENCES public.resources(id) ON DELETE CASCADE,
  skill_name    text NOT NULL,
  skill_node_id uuid REFERENCES public.skill_nodes(id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (resource_id, skill_name)
);
GRANT SELECT ON public.resource_skills TO anon, authenticated;
GRANT ALL ON public.resource_skills TO service_role;
ALTER TABLE public.resource_skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Resource skills are public" ON public.resource_skills FOR SELECT USING (true);
CREATE POLICY "Admins manage resource skills" ON public.resource_skills FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE INDEX idx_resource_skills_name ON public.resource_skills (lower(skill_name));
CREATE INDEX idx_resource_skills_node ON public.resource_skills (skill_node_id);

-- ============================================================
-- ZONE A: identity consolidation
-- ============================================================

CREATE TABLE public.user_settings (
  user_id             uuid PRIMARY KEY,
  profile_visibility  text NOT NULL DEFAULT 'public',
  show_online_status  boolean NOT NULL DEFAULT true,
  allow_follow_requests boolean NOT NULL DEFAULT true,
  email_notifications boolean NOT NULL DEFAULT true,
  push_notifications  boolean NOT NULL DEFAULT true,
  marketing_emails    boolean NOT NULL DEFAULT false,
  login_notifications boolean NOT NULL DEFAULT true,
  two_factor_enabled  boolean NOT NULL DEFAULT false,
  theme               text NOT NULL DEFAULT 'system',
  language            text NOT NULL DEFAULT 'en',
  timezone            text,
  primary_domain      text,
  interests           text[] NOT NULL DEFAULT '{}',
  interested_domains  text[] NOT NULL DEFAULT '{}',
  interested_subdomains text[] NOT NULL DEFAULT '{}',
  experience_level    text,
  skills              jsonb NOT NULL DEFAULT '[]'::jsonb,
  social_links        jsonb NOT NULL DEFAULT '{}'::jsonb,
  portfolio_url       text,
  company             text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.user_settings TO authenticated;
GRANT ALL ON public.user_settings TO service_role;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own settings"
  ON public.user_settings FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE TRIGGER trg_user_settings_updated_at BEFORE UPDATE ON public.user_settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- BACKFILL (stage 2)
-- ============================================================

INSERT INTO public.resource_stats (
  resource_id, avg_rating, weighted_rating, total_ratings,
  recommend_percent, total_votes, total_reviews, view_count
)
SELECT id, avg_rating, weighted_rating, COALESCE(total_ratings,0),
       recommend_percent, COALESCE(total_votes,0), COALESCE(total_reviews,0), 0
FROM public.resources
ON CONFLICT (resource_id) DO NOTHING;

INSERT INTO public.resource_skills (resource_id, skill_name, skill_node_id)
SELECT DISTINCT r.id, btrim(s) AS skill_name,
       (SELECT sn.id FROM public.skill_nodes sn WHERE lower(sn.name) = lower(btrim(s)) LIMIT 1)
FROM public.resources r
CROSS JOIN LATERAL unnest(COALESCE(r.related_skills, '{}')) AS s
WHERE btrim(s) <> ''
ON CONFLICT (resource_id, skill_name) DO NOTHING;

INSERT INTO public.user_settings (
  user_id, profile_visibility, show_online_status, allow_follow_requests,
  email_notifications, push_notifications, marketing_emails, login_notifications,
  two_factor_enabled, theme, language, timezone, primary_domain, interests,
  interested_domains, interested_subdomains, experience_level, skills,
  social_links, portfolio_url, company
)
SELECT
  p.user_id,
  COALESCE(up.profile_visibility, 'public'),
  COALESCE(up.show_online_status, true),
  COALESCE(up.allow_follow_requests, true),
  COALESCE(up.email_notifications, true),
  COALESCE(up.push_notifications, true),
  COALESCE(up.marketing_emails, false),
  COALESCE(up.login_notifications, true),
  COALESCE(up.two_factor_enabled, false),
  COALESCE(up.theme, 'system'),
  COALESCE(up.language, 'en'),
  up.timezone,
  up.primary_domain,
  COALESCE(up.interests, '{}'),
  COALESCE(upd.interested_domains, '{}'),
  COALESCE(upd.interested_subdomains, '{}'),
  upd.experience_level,
  COALESCE(upd.skills, '[]'::jsonb),
  COALESCE(upd.social_links, '{}'::jsonb),
  upd.portfolio_url,
  upd.company
FROM public.profiles p
LEFT JOIN public.user_preferences up ON up.user_id = p.user_id
LEFT JOIN public.user_profile_details upd ON upd.user_id = p.user_id
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO public.saved_items (user_id, subject_type, subject_id, collection_id, notes, created_at)
SELECT sp.user_id, 'post'::public.interaction_subject, sp.post_id, sp.collection_id, sp.notes, sp.created_at
FROM public.saved_posts sp
ON CONFLICT (user_id, subject_type, subject_id) DO NOTHING;

INSERT INTO public.saved_items (user_id, subject_type, subject_id, created_at)
SELECT b.user_id, 'post'::public.interaction_subject, b.post_id, b.created_at
FROM public.bookmarks b
ON CONFLICT (user_id, subject_type, subject_id) DO NOTHING;

INSERT INTO public.post_engagement (user_id, post_id, created_at)
SELECT l.user_id, l.post_id, l.created_at
FROM public.likes l
ON CONFLICT (user_id, post_id) DO NOTHING;

-- events: legacy user_activity
INSERT INTO public.interaction_events (user_id, subject_type, subject_id, event_type, surface, context, occurred_at, created_at)
SELECT ua.user_id,
       CASE WHEN ua.post_id IS NOT NULL THEN 'post'
            WHEN ua.roadmap_id IS NOT NULL THEN 'roadmap'
            WHEN ua.target_user_id IS NOT NULL THEN 'profile'
            ELSE 'resource' END::public.interaction_subject,
       COALESCE(ua.post_id, ua.roadmap_id, ua.target_user_id),
       CASE ua.activity_type
         WHEN 'like' THEN 'like' WHEN 'unlike' THEN 'unlike'
         WHEN 'comment' THEN 'comment' WHEN 'share' THEN 'share'
         WHEN 'save' THEN 'save' WHEN 'search' THEN 'search'
         WHEN 'download' THEN 'download' WHEN 'complete' THEN 'complete'
         WHEN 'view' THEN 'open' WHEN 'click' THEN 'click'
         ELSE 'open' END::public.interaction_verb,
       'legacy.user_activity',
       COALESCE(ua.metadata, '{}'::jsonb) || jsonb_build_object('legacy_activity_type', ua.activity_type, 'device_type', ua.device_type),
       ua.created_at, ua.created_at
FROM public.user_activity ua;

-- events: interactions_ml
INSERT INTO public.interaction_events (user_id, subject_type, subject_id, event_type, surface, context, occurred_at, created_at)
SELECT im.user_id,
       CASE WHEN im.item_type = 'post' THEN 'post'
            WHEN im.item_type = 'roadmap' THEN 'roadmap'
            ELSE 'resource' END::public.interaction_subject,
       im.item_id,
       CASE im.interaction_type
         WHEN 'like' THEN 'like' WHEN 'save' THEN 'save' WHEN 'share' THEN 'share'
         WHEN 'rate' THEN 'rate' WHEN 'vote' THEN 'vote' WHEN 'click' THEN 'click'
         WHEN 'view' THEN 'open' ELSE 'open' END::public.interaction_verb,
       'legacy.interactions_ml',
       COALESCE(im.metadata, '{}'::jsonb) || jsonb_build_object('legacy_score', im.score, 'legacy_interaction_type', im.interaction_type),
       COALESCE(im.created_at, now()), COALESCE(im.created_at, now())
FROM public.interactions_ml im;

-- events: seen resources -> impressions
INSERT INTO public.interaction_events (user_id, subject_type, subject_id, event_type, surface, occurred_at, created_at)
SELECT usr.user_id, 'resource', usr.resource_id, 'impression', 'legacy.seen',
       COALESCE(usr.seen_at, now()), COALESCE(usr.seen_at, now())
FROM public.user_seen_resources usr;

-- events: recommendation_events
INSERT INTO public.interaction_events (user_id, subject_type, subject_id, event_type, surface, position, model_version, context, occurred_at, created_at)
SELECT re.user_id, 'resource', re.resource_id,
       CASE re.event_type WHEN 'click' THEN 'click' WHEN 'impression' THEN 'impression'
            WHEN 'save' THEN 'save' ELSE 'impression' END::public.interaction_verb,
       COALESCE(re.surface, 'legacy.recommendations'), re.rank_position, re.model_version,
       jsonb_build_object('reason', re.reason),
       re.created_at, re.created_at
FROM public.recommendation_events re;

-- events: likes / bookmarks / votes / ratings
INSERT INTO public.interaction_events (user_id, subject_type, subject_id, event_type, surface, occurred_at, created_at)
SELECT l.user_id, 'post', l.post_id, 'like', 'legacy.likes', l.created_at, l.created_at FROM public.likes l;

INSERT INTO public.interaction_events (user_id, subject_type, subject_id, event_type, surface, occurred_at, created_at)
SELECT b.user_id, 'post', b.post_id, 'save', 'legacy.bookmarks', b.created_at, b.created_at FROM public.bookmarks b;

INSERT INTO public.interaction_events (user_id, subject_type, subject_id, event_type, surface, context, occurred_at, created_at)
SELECT rv.user_id, 'resource', rv.resource_id, 'vote', 'legacy.votes',
       jsonb_build_object('vote_type', rv.vote_type), rv.created_at, rv.created_at
FROM public.resource_votes rv;

INSERT INTO public.interaction_events (user_id, subject_type, subject_id, event_type, surface, context, occurred_at, created_at)
SELECT rr.user_id, 'resource', rr.resource_id, 'rate', 'legacy.ratings',
       jsonb_build_object('stars', rr.stars), rr.created_at, rr.created_at
FROM public.resource_ratings rr;

-- ============================================================
-- TRAINING VIEWS (model contracts)
-- ============================================================

CREATE OR REPLACE VIEW public.v_user_item_implicit
WITH (security_invoker = true) AS
SELECT
  e.user_id,
  e.subject_id AS resource_id,
  ROUND(SUM(
    CASE e.event_type
      WHEN 'impression' THEN 0.1
      WHEN 'click'      THEN 1.0
      WHEN 'open'       THEN 1.5
      WHEN 'download'   THEN 3.0
      WHEN 'save'       THEN 3.0
      WHEN 'share'      THEN 3.5
      WHEN 'like'       THEN 2.5
      WHEN 'comment'    THEN 3.0
      WHEN 'rate'       THEN 4.0
      WHEN 'vote'       THEN 2.0
      WHEN 'complete'   THEN 5.0
      WHEN 'unlike'     THEN -2.5
      WHEN 'unsave'     THEN -3.0
      ELSE 0.0
    END
    * exp(-0.0077 * GREATEST(EXTRACT(EPOCH FROM (now() - e.occurred_at)) / 86400.0, 0))
  )::numeric + COALESCE(SUM(ln(1 + COALESCE(e.dwell_ms, 0) / 1000.0)), 0)::numeric, 4) AS score,
  COUNT(*) AS event_count,
  MAX(e.occurred_at) AS last_seen_at
FROM public.interaction_events e
WHERE e.subject_type = 'resource' AND e.subject_id IS NOT NULL
GROUP BY e.user_id, e.subject_id;

CREATE OR REPLACE VIEW public.v_session_sequences
WITH (security_invoker = true) AS
SELECT
  e.user_id,
  e.session_id,
  MIN(e.occurred_at) AS started_at,
  MAX(e.occurred_at) AS ended_at,
  COUNT(*) AS event_count,
  SUM(COALESCE(e.dwell_ms, 0)) AS total_dwell_ms,
  ARRAY_AGG(e.subject_id ORDER BY e.sequence_no NULLS LAST, e.occurred_at) AS subject_path,
  ARRAY_AGG(e.event_type::text ORDER BY e.sequence_no NULLS LAST, e.occurred_at) AS verb_path,
  ARRAY_AGG(COALESCE(e.surface, '') ORDER BY e.sequence_no NULLS LAST, e.occurred_at) AS surface_path
FROM public.interaction_events e
WHERE e.session_id IS NOT NULL
GROUP BY e.user_id, e.session_id;

CREATE OR REPLACE VIEW public.v_resource_features
WITH (security_invoker = true) AS
SELECT
  r.id AS resource_id,
  r.title, r.description, r.link, r.provider,
  r.resource_type, r.section_type,
  r.domain, r.subdomain, r.category,
  r.difficulty, r.language, r.duration, r.estimated_time,
  r.is_free, r.is_featured, r.is_active, r.created_at,
  COALESCE(ARRAY(
    SELECT rs.skill_name FROM public.resource_skills rs WHERE rs.resource_id = r.id ORDER BY rs.skill_name
  ), '{}') AS skills,
  st.avg_rating, st.weighted_rating, st.total_ratings,
  st.recommend_percent, st.total_votes, st.total_reviews,
  st.view_count, st.click_count, st.total_dwell_ms
FROM public.resources r
LEFT JOIN public.resource_stats st ON st.resource_id = r.id;

GRANT SELECT ON public.v_resource_features TO anon, authenticated;
GRANT SELECT ON public.v_resource_features TO service_role;
GRANT SELECT ON public.v_user_item_implicit TO authenticated, service_role;
GRANT SELECT ON public.v_session_sequences TO authenticated, service_role;

CREATE OR REPLACE VIEW public.v_recommendation_outcomes
WITH (security_invoker = true) AS
SELECT
  imp.user_id,
  imp.subject_id AS resource_id,
  imp.surface,
  imp.variant,
  imp.model_version,
  imp.position,
  imp.occurred_at AS impressed_at,
  EXISTS (
    SELECT 1 FROM public.interaction_events c
    WHERE c.user_id = imp.user_id
      AND c.subject_id = imp.subject_id
      AND c.event_type IN ('click','open','save','download','complete')
      AND c.occurred_at BETWEEN imp.occurred_at AND imp.occurred_at + interval '1 hour'
  ) AS converted
FROM public.interaction_events imp
WHERE imp.event_type = 'impression' AND imp.subject_type = 'resource';

GRANT SELECT ON public.v_recommendation_outcomes TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.track_interaction(public.interaction_subject, public.interaction_verb, uuid, uuid, text, integer, integer, text, text, jsonb) FROM anon;
GRANT EXECUTE ON FUNCTION public.track_interaction(public.interaction_subject, public.interaction_verb, uuid, uuid, text, integer, integer, text, text, jsonb) TO authenticated;