
-- Insert massive resource data for underrepresented domains and exams

-- ==================== FINANCE (12 new) ====================
INSERT INTO resources (title, description, link, category, difficulty, is_free, resource_type, section_type, provider, duration, is_active, is_featured, related_skills, education_levels) VALUES
('Financial Markets by Yale', 'Robert Shiller''s comprehensive course on financial markets, risk management, and behavioral finance', 'https://www.coursera.org/learn/financial-markets-global', 'Finance', 'beginner', true, 'course', 'domain', 'Coursera / Yale', '33 hours', true, true, ARRAY['investing','risk management','behavioral finance'], ARRAY['bachelors','masters']),
('Corporate Finance Essentials', 'Learn corporate finance fundamentals including valuation, capital budgeting, and financial analysis', 'https://www.edx.org/course/corporate-finance', 'Finance', 'intermediate', true, 'course', 'domain', 'edX / Columbia', '24 hours', true, false, ARRAY['corporate finance','valuation','capital budgeting'], ARRAY['bachelors','masters']),
('Khan Academy - Finance & Capital Markets', 'Free comprehensive finance education covering stocks, bonds, investment, and banking', 'https://www.khanacademy.org/economics-finance-domain/core-finance', 'Finance', 'beginner', true, 'course', 'domain', 'Khan Academy', '40 hours', true, false, ARRAY['stocks','bonds','banking','investment'], ARRAY['high-school','bachelors']),
('CFA Level 1 Preparation Guide', 'Complete preparation guide for CFA Level 1 exam covering ethics, economics, and financial reporting', 'https://www.cfainstitute.org/en/programs/cfa', 'Finance', 'advanced', false, 'certification', 'domain', 'CFA Institute', '300 hours', true, true, ARRAY['CFA','financial analysis','portfolio management'], ARRAY['bachelors','masters']),
('Financial Modeling & Valuation Analyst', 'Industry-recognized financial modeling certification with Excel and real-world case studies', 'https://corporatefinanceinstitute.com/certifications/fmva/', 'Finance', 'intermediate', false, 'certification', 'domain', 'CFI', '120 hours', true, false, ARRAY['financial modeling','Excel','valuation'], ARRAY['bachelors','masters']),
('Personal Finance 101', 'BYU course on budgeting, saving, credit, and retirement planning', 'https://www.coursera.org/learn/personal-finance', 'Finance', 'beginner', true, 'course', 'domain', 'Coursera / BYU', '15 hours', true, false, ARRAY['budgeting','saving','retirement','credit'], ARRAY['high-school','bachelors']),
('Python for Finance', 'Use Python for financial analysis, algorithmic trading, and portfolio optimization', 'https://www.udemy.com/course/python-for-finance-trading/', 'Finance', 'intermediate', false, 'course', 'domain', 'Udemy', '18 hours', true, false, ARRAY['Python','algorithmic trading','portfolio optimization'], ARRAY['bachelors','masters']),
('Bloomberg Market Concepts', 'Self-paced e-learning covering economics, currencies, fixed income, and equities', 'https://www.bloomberg.com/professional/product/bloomberg-market-concepts/', 'Finance', 'beginner', false, 'certification', 'domain', 'Bloomberg', '8 hours', true, true, ARRAY['economics','equities','fixed income','currencies'], ARRAY['bachelors','masters']),
('Financial Accounting - UVA', 'University of Virginia course on financial statements and accounting principles', 'https://www.coursera.org/learn/uva-darden-financial-accounting', 'Finance', 'beginner', true, 'course', 'domain', 'Coursera / UVA', '13 hours', true, false, ARRAY['accounting','financial statements','GAAP'], ARRAY['bachelors']),
('Blockchain and Fintech', 'Understand DeFi, cryptocurrency markets, and blockchain technology in finance', 'https://www.edx.org/course/blockchain-and-fintech', 'Finance', 'intermediate', true, 'course', 'domain', 'edX / HKU', '12 hours', true, false, ARRAY['blockchain','DeFi','cryptocurrency'], ARRAY['bachelors','masters']),
('Investment Management Specialization', 'Geneva Finance Research Institute program on portfolio construction and risk management', 'https://www.coursera.org/specializations/investment-management', 'Finance', 'advanced', true, 'learning_path', 'domain', 'Coursera / Geneva', '40 hours', true, false, ARRAY['portfolio management','risk analysis','asset allocation'], ARRAY['masters']),
('Financial Risk Management - GARP', 'FRM certification prep covering market risk, credit risk, and operational risk', 'https://www.garp.org/frm', 'Finance', 'advanced', false, 'certification', 'domain', 'GARP', '200 hours', true, false, ARRAY['risk management','FRM','market risk','credit risk'], ARRAY['masters']),

-- ==================== BUSINESS (12 new) ====================
('Business Foundations - Wharton', 'Comprehensive business fundamentals covering marketing, accounting, operations, and finance', 'https://www.coursera.org/specializations/wharton-business-foundations', 'Business', 'beginner', true, 'learning_path', 'domain', 'Coursera / Wharton', '32 hours', true, true, ARRAY['marketing','accounting','operations','strategy'], ARRAY['bachelors']),
('Entrepreneurship Specialization', 'Launch your startup with Wharton''s program covering opportunity, launch, growth, and financing', 'https://www.coursera.org/specializations/wharton-entrepreneurship', 'Business', 'intermediate', true, 'learning_path', 'domain', 'Coursera / Wharton', '20 hours', true, true, ARRAY['entrepreneurship','startup','venture capital'], ARRAY['bachelors','masters']),
('HBS Online CORe', 'Credential of Readiness covering business analytics, economics, and financial accounting', 'https://online.hbs.edu/courses/core/', 'Business', 'intermediate', false, 'certification', 'domain', 'Harvard Business School', '150 hours', true, true, ARRAY['business analytics','economics','financial accounting'], ARRAY['bachelors','masters']),
('Business Strategy - UVA', 'Learn to analyze competitive dynamics and develop winning strategies', 'https://www.coursera.org/specializations/business-strategy', 'Business', 'intermediate', true, 'course', 'domain', 'Coursera / UVA', '24 hours', true, false, ARRAY['strategy','competitive analysis','business growth'], ARRAY['bachelors','masters']),
('Supply Chain Management', 'Rutgers course on supply chain design, planning, logistics, and operations', 'https://www.coursera.org/specializations/supply-chain-management', 'Business', 'intermediate', true, 'learning_path', 'domain', 'Coursera / Rutgers', '28 hours', true, false, ARRAY['supply chain','logistics','operations'], ARRAY['bachelors','masters']),
('Business Analytics with Excel', 'Master data-driven decisions using Excel, pivot tables, and statistical analysis', 'https://www.coursera.org/specializations/business-analytics-excel', 'Business', 'beginner', true, 'course', 'domain', 'Coursera / Rice', '16 hours', true, false, ARRAY['Excel','data analysis','business intelligence'], ARRAY['bachelors']),
('International Business - UoL', 'Global business operations, trade, and cross-cultural management', 'https://www.coursera.org/learn/international-business', 'Business', 'intermediate', true, 'course', 'domain', 'Coursera / UoL', '15 hours', true, false, ARRAY['international business','global trade'], ARRAY['bachelors','masters']),
('E-Commerce Business Masterclass', 'Build and scale an e-commerce business from sourcing to marketing', 'https://www.udemy.com/course/ecommerce-masterclass/', 'Business', 'beginner', false, 'course', 'domain', 'Udemy', '14 hours', true, false, ARRAY['e-commerce','Shopify','online business'], ARRAY['high-school','bachelors']),
('Operations Management - UIUC', 'Learn process analysis, quality management, and inventory control', 'https://www.coursera.org/learn/operations-management', 'Business', 'intermediate', true, 'course', 'domain', 'Coursera / UIUC', '20 hours', true, false, ARRAY['operations','process analysis','quality management'], ARRAY['bachelors']),
('Negotiation Mastery - HBS', 'Harvard negotiation strategies for business deals and conflict resolution', 'https://online.hbs.edu/courses/negotiation-mastery/', 'Business', 'intermediate', false, 'course', 'domain', 'Harvard Business School', '8 weeks', true, false, ARRAY['negotiation','conflict resolution','deal-making'], ARRAY['bachelors','masters']),
('Business Model Canvas Workshop', 'Learn to design and iterate business models using the Business Model Canvas framework', 'https://www.strategyzer.com/training', 'Business', 'beginner', false, 'course', 'domain', 'Strategyzer', '10 hours', true, false, ARRAY['business model','canvas','value proposition'], ARRAY['bachelors']),
('Google Project Management Certificate', 'Professional certificate in project management methodologies, Agile, and Scrum', 'https://www.coursera.org/professional-certificates/google-project-management', 'Business', 'beginner', true, 'certification', 'domain', 'Coursera / Google', '6 months', true, true, ARRAY['project management','Agile','Scrum'], ARRAY['bachelors']),

-- ==================== MARKETING (12 new) ====================
('Google Digital Marketing Certificate', 'Professional certificate covering SEO, SEM, social media, email marketing, and analytics', 'https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce', 'Marketing', 'beginner', true, 'certification', 'domain', 'Coursera / Google', '6 months', true, true, ARRAY['SEO','SEM','social media','email marketing'], ARRAY['bachelors']),
('HubSpot Inbound Marketing', 'Free certification on inbound marketing methodology, content strategy, and lead nurturing', 'https://academy.hubspot.com/courses/inbound-marketing', 'Marketing', 'beginner', true, 'certification', 'domain', 'HubSpot Academy', '6 hours', true, true, ARRAY['inbound marketing','content strategy','lead generation'], ARRAY['bachelors']),
('Meta Social Media Marketing', 'Professional certificate from Meta covering Facebook, Instagram, and social media advertising', 'https://www.coursera.org/professional-certificates/facebook-social-media-marketing', 'Marketing', 'beginner', true, 'certification', 'domain', 'Coursera / Meta', '7 months', true, true, ARRAY['social media','Facebook ads','Instagram','advertising'], ARRAY['bachelors']),
('SEO Training - Moz', 'Comprehensive SEO training covering keyword research, link building, and technical SEO', 'https://moz.com/training', 'Marketing', 'intermediate', true, 'course', 'domain', 'Moz', '10 hours', true, false, ARRAY['SEO','keyword research','link building','technical SEO'], ARRAY['bachelors']),
('Content Marketing Masterclass', 'Learn to create compelling content that drives traffic, engagement, and conversions', 'https://www.udemy.com/course/content-marketing-masterclass/', 'Marketing', 'intermediate', false, 'course', 'domain', 'Udemy', '12 hours', true, false, ARRAY['content marketing','blogging','copywriting'], ARRAY['bachelors']),
('Google Analytics Certification', 'Master Google Analytics 4 for tracking, measuring, and reporting website performance', 'https://skillshop.withgoogle.com/googleanalytics', 'Marketing', 'intermediate', true, 'certification', 'domain', 'Google Skillshop', '15 hours', true, false, ARRAY['Google Analytics','data analysis','web analytics'], ARRAY['bachelors']),
('Email Marketing with Mailchimp', 'Build effective email campaigns, automation sequences, and subscriber growth strategies', 'https://www.udemy.com/course/email-marketing-with-mailchimp/', 'Marketing', 'beginner', false, 'course', 'domain', 'Udemy', '8 hours', true, false, ARRAY['email marketing','Mailchimp','automation'], ARRAY['bachelors']),
('Brand Management - University of London', 'Strategic brand management including brand equity, positioning, and brand architecture', 'https://www.coursera.org/learn/brand-management', 'Marketing', 'intermediate', true, 'course', 'domain', 'Coursera / UoL', '18 hours', true, false, ARRAY['brand management','brand equity','positioning'], ARRAY['bachelors','masters']),
('Growth Hacking & Marketing Automation', 'Learn growth strategies used by startups - viral loops, A/B testing, and funnel optimization', 'https://www.udemy.com/course/growth-hacking-masterclass/', 'Marketing', 'advanced', false, 'course', 'domain', 'Udemy', '10 hours', true, false, ARRAY['growth hacking','A/B testing','funnel optimization'], ARRAY['bachelors']),
('Copywriting Secrets - Direct Response', 'Master persuasive writing techniques for ads, landing pages, and sales letters', 'https://www.udemy.com/course/copywriting-secrets/', 'Marketing', 'intermediate', false, 'course', 'domain', 'Udemy', '7 hours', true, false, ARRAY['copywriting','direct response','persuasion'], ARRAY['bachelors']),
('Digital Advertising - Google Ads', 'Complete guide to Google Ads including search, display, video, and shopping campaigns', 'https://www.udemy.com/course/google-ads-course/', 'Marketing', 'intermediate', false, 'course', 'domain', 'Udemy', '20 hours', true, false, ARRAY['Google Ads','PPC','display advertising'], ARRAY['bachelors']),
('Marketing Analytics - UVA', 'Data-driven marketing using regression, A/B testing, and customer lifetime value models', 'https://www.coursera.org/specializations/marketing-analytics', 'Marketing', 'advanced', true, 'learning_path', 'domain', 'Coursera / UVA', '24 hours', true, false, ARRAY['marketing analytics','CLV','regression','attribution'], ARRAY['bachelors','masters']),

-- ==================== MANAGEMENT (12 new) ====================
('Leading People and Teams - Michigan', 'University of Michigan course on leadership, team dynamics, and organizational behavior', 'https://www.coursera.org/specializations/leading-teams', 'Management', 'intermediate', true, 'learning_path', 'domain', 'Coursera / Michigan', '20 hours', true, true, ARRAY['leadership','team management','organizational behavior'], ARRAY['bachelors','masters']),
('PMP Certification Prep', 'Complete Project Management Professional certification preparation with practice exams', 'https://www.udemy.com/course/pmp-certification-exam-prep/', 'Management', 'advanced', false, 'exam_prep', 'domain', 'Udemy', '35 hours', true, true, ARRAY['PMP','project management','PMBOK'], ARRAY['bachelors','masters']),
('Agile with Atlassian Jira', 'Learn Agile project management with hands-on Jira experience for Scrum and Kanban', 'https://www.coursera.org/learn/agile-atlassian-jira', 'Management', 'beginner', true, 'course', 'domain', 'Coursera / Atlassian', '12 hours', true, false, ARRAY['Agile','Jira','Scrum','Kanban'], ARRAY['bachelors']),
('Strategic Leadership - Dartmouth', 'Tuck School course on strategic thinking, decision-making, and organizational leadership', 'https://www.coursera.org/learn/strategic-leadership', 'Management', 'advanced', true, 'course', 'domain', 'Coursera / Dartmouth', '16 hours', true, false, ARRAY['strategic leadership','decision-making','organizational design'], ARRAY['masters']),
('HR Management - People Analytics', 'Use data analytics for HR decisions including recruitment, retention, and workforce planning', 'https://www.coursera.org/specializations/people-analytics', 'Management', 'intermediate', true, 'learning_path', 'domain', 'Coursera / Wharton', '20 hours', true, false, ARRAY['HR analytics','recruitment','retention','workforce planning'], ARRAY['bachelors','masters']),
('Six Sigma Green Belt Certification', 'Learn DMAIC methodology, process improvement, and statistical quality control', 'https://www.udemy.com/course/lean-six-sigma-green-belt/', 'Management', 'intermediate', false, 'certification', 'domain', 'Udemy', '25 hours', true, false, ARRAY['Six Sigma','DMAIC','process improvement','quality control'], ARRAY['bachelors','masters']),
('Change Management Foundations', 'Master organizational change management including stakeholder engagement and communication', 'https://www.linkedin.com/learning/change-management-foundations', 'Management', 'intermediate', false, 'course', 'domain', 'LinkedIn Learning', '8 hours', true, false, ARRAY['change management','stakeholder engagement','organizational change'], ARRAY['bachelors','masters']),
('Conflict Resolution Skills', 'Practical conflict resolution, mediation, and difficult conversations in workplace settings', 'https://www.coursera.org/learn/conflict-resolution', 'Management', 'beginner', true, 'course', 'domain', 'Coursera / UCI', '10 hours', true, false, ARRAY['conflict resolution','mediation','communication'], ARRAY['bachelors']),
('OKR Goal Setting Framework', 'Implement Objectives and Key Results methodology used by Google, Intel, and top companies', 'https://www.udemy.com/course/okr-goal-setting/', 'Management', 'beginner', false, 'course', 'domain', 'Udemy', '5 hours', true, false, ARRAY['OKR','goal setting','performance management'], ARRAY['bachelors']),
('Product Management Certificate', 'End-to-end product management from discovery to launch with real-world frameworks', 'https://www.productschool.com/product-management-certification/', 'Management', 'intermediate', false, 'certification', 'domain', 'Product School', '40 hours', true, true, ARRAY['product management','roadmap','user research','prioritization'], ARRAY['bachelors','masters']),
('Remote Team Management', 'Best practices for managing distributed teams including communication, productivity, and culture', 'https://www.coursera.org/learn/remote-team-management', 'Management', 'beginner', true, 'course', 'domain', 'Coursera / GitLab', '8 hours', true, false, ARRAY['remote work','team management','distributed teams'], ARRAY['bachelors']),
('Executive Leadership Program - MIT', 'MIT Sloan executive program on innovation, digital transformation, and strategic leadership', 'https://executive.mit.edu/course/executive-leadership/', 'Management', 'expert', false, 'course', 'domain', 'MIT Sloan', '12 weeks', true, false, ARRAY['executive leadership','innovation','digital transformation'], ARRAY['masters','phd']),

-- ==================== COMMUNICATION (12 new) ====================
('Improve Your English Communication', 'Georgia Tech course on professional English communication for non-native speakers', 'https://www.coursera.org/specializations/improve-english', 'Communication', 'beginner', true, 'learning_path', 'domain', 'Coursera / Georgia Tech', '20 hours', true, true, ARRAY['English','professional communication','writing'], ARRAY['high-school','bachelors']),
('Public Speaking Specialization', 'University of Washington course on speech writing, delivery, and overcoming stage fright', 'https://www.coursera.org/specializations/public-speaking', 'Communication', 'beginner', true, 'learning_path', 'domain', 'Coursera / UW', '16 hours', true, true, ARRAY['public speaking','presentation','speech writing'], ARRAY['high-school','bachelors']),
('Business Writing - UC Boulder', 'Professional writing skills for emails, reports, proposals, and executive summaries', 'https://www.coursera.org/learn/writing-for-business', 'Communication', 'intermediate', true, 'course', 'domain', 'Coursera / UC Boulder', '12 hours', true, false, ARRAY['business writing','emails','reports','proposals'], ARRAY['bachelors']),
('Storytelling and Influence', 'Master the art of storytelling for business presentations, pitches, and leadership communication', 'https://www.coursera.org/learn/storytelling-influence', 'Communication', 'intermediate', true, 'course', 'domain', 'Coursera / Macquarie', '10 hours', true, false, ARRAY['storytelling','influence','presentations','pitching'], ARRAY['bachelors','masters']),
('Technical Writing Fundamentals', 'Google''s free technical writing course for software engineers and technical professionals', 'https://developers.google.com/tech-writing', 'Communication', 'beginner', true, 'course', 'domain', 'Google', '6 hours', true, false, ARRAY['technical writing','documentation','clarity'], ARRAY['bachelors']),
('Interpersonal Communication Skills', 'Develop active listening, empathy, and assertive communication for workplace success', 'https://www.coursera.org/learn/interpersonal-communication', 'Communication', 'beginner', true, 'course', 'domain', 'Coursera / UIUC', '8 hours', true, false, ARRAY['active listening','empathy','assertiveness','interpersonal skills'], ARRAY['high-school','bachelors']),
('Cross-Cultural Communication', 'Navigate cultural differences in global business settings and multicultural teams', 'https://www.edx.org/course/cross-cultural-communication', 'Communication', 'intermediate', true, 'course', 'domain', 'edX / TU Delft', '10 hours', true, false, ARRAY['cross-cultural','global communication','cultural intelligence'], ARRAY['bachelors','masters']),
('Academic Writing Made Easy', 'Learn research paper writing, citation management, and academic publishing', 'https://www.coursera.org/learn/academic-writing', 'Communication', 'intermediate', true, 'course', 'domain', 'Coursera / UCI', '14 hours', true, false, ARRAY['academic writing','research papers','citations'], ARRAY['bachelors','masters','phd']),
('Negotiation and Persuasion', 'Yale course on principles of negotiation, persuasion tactics, and ethical influence', 'https://www.coursera.org/learn/negotiation', 'Communication', 'intermediate', true, 'course', 'domain', 'Coursera / Yale', '12 hours', true, false, ARRAY['negotiation','persuasion','influence'], ARRAY['bachelors','masters']),
('Media Training for Professionals', 'Prepare for media interviews, press conferences, and crisis communication', 'https://www.udemy.com/course/media-training/', 'Communication', 'advanced', false, 'course', 'domain', 'Udemy', '6 hours', true, false, ARRAY['media training','press','crisis communication'], ARRAY['bachelors','masters']),
('Grant Writing Essentials', 'Write winning grant proposals for research funding and nonprofit organizations', 'https://www.udemy.com/course/grant-writing/', 'Communication', 'intermediate', false, 'course', 'domain', 'Udemy', '8 hours', true, false, ARRAY['grant writing','proposals','research funding'], ARRAY['bachelors','masters','phd']),
('Presentation Design with PowerPoint', 'Create visually stunning presentations with advanced PowerPoint techniques and design principles', 'https://www.udemy.com/course/powerpoint-design/', 'Communication', 'beginner', false, 'course', 'domain', 'Udemy', '10 hours', true, false, ARRAY['PowerPoint','presentation design','visual communication'], ARRAY['high-school','bachelors']),

-- ==================== PYTHON (8 new to boost from 5) ====================
('Python for Everybody - Michigan', 'University of Michigan''s most popular Python course covering data structures, web scraping, and databases', 'https://www.coursera.org/specializations/python', 'Python', 'beginner', true, 'learning_path', 'domain', 'Coursera / Michigan', '40 hours', true, true, ARRAY['Python','data structures','web scraping','databases'], ARRAY['high-school','bachelors']),
('Automate the Boring Stuff with Python', 'Practical Python programming for automating everyday tasks - files, web, Excel, and more', 'https://automatetheboringstuff.com/', 'Python', 'beginner', true, 'book', 'domain', 'Al Sweigart', '20 hours', true, true, ARRAY['Python','automation','scripting','web scraping'], ARRAY['high-school','bachelors']),
('Python Data Structures & Algorithms', 'Master DSA with Python including linked lists, trees, graphs, sorting, and dynamic programming', 'https://www.udemy.com/course/python-data-structures-algorithms/', 'Python', 'intermediate', false, 'course', 'domain', 'Udemy', '16 hours', true, false, ARRAY['DSA','algorithms','data structures','Python'], ARRAY['bachelors']),
('Django for Beginners', 'Build modern web applications with Django - from setup to deployment', 'https://djangoforbeginners.com/', 'Python', 'intermediate', false, 'book', 'domain', 'William Vincent', '15 hours', true, false, ARRAY['Django','web development','REST API','Python'], ARRAY['bachelors']),
('FastAPI Modern Python Web Framework', 'Build high-performance APIs with FastAPI, Pydantic, and async Python', 'https://www.udemy.com/course/fastapi-course/', 'Python', 'intermediate', false, 'course', 'domain', 'Udemy', '12 hours', true, false, ARRAY['FastAPI','REST API','async','Pydantic'], ARRAY['bachelors']),
('Python Machine Learning - scikit-learn', 'Hands-on ML with Python covering classification, regression, clustering, and model evaluation', 'https://www.coursera.org/learn/python-machine-learning', 'Python', 'intermediate', true, 'course', 'domain', 'Coursera / Michigan', '25 hours', true, false, ARRAY['machine learning','scikit-learn','classification','regression'], ARRAY['bachelors','masters']),
('Python Testing with pytest', 'Master Python testing including unit tests, fixtures, mocking, and CI/CD integration', 'https://www.udemy.com/course/python-testing-pytest/', 'Python', 'intermediate', false, 'course', 'domain', 'Udemy', '8 hours', true, false, ARRAY['pytest','testing','CI/CD','TDD'], ARRAY['bachelors']),
('Advanced Python Programming', 'Deep dive into decorators, metaclasses, generators, concurrency, and design patterns', 'https://www.udemy.com/course/advanced-python-programming/', 'Python', 'advanced', false, 'course', 'domain', 'Udemy', '14 hours', true, false, ARRAY['decorators','metaclasses','concurrency','design patterns'], ARRAY['bachelors','masters']);
