
-- MORE DOMAIN RESOURCES: Mobile Development, UI/UX Design, Blockchain, Digital Marketing, Finance, Project Management

-- MOBILE DEVELOPMENT RESOURCES (12)
INSERT INTO resources (title, description, link, category, difficulty, is_free, icon, color, resource_type, section_type, provider, duration, related_skills, relevant_backgrounds, avg_rating, weighted_rating, total_ratings, recommend_percent, total_votes) VALUES
('Flutter Official Docs', 'Build beautiful native apps with Flutter', 'https://docs.flutter.dev', 'Mobile Development', 'beginner', true, '💙', 'blue', 'website', 'domain', 'Google', 'Self-paced', ARRAY['Flutter', 'Dart', 'Cross-platform'], ARRAY['Developer'], 4.85, 4.80, 18000, 97, 17500),
('React Native Docs', 'Build native mobile apps using React', 'https://reactnative.dev/docs/getting-started', 'Mobile Development', 'intermediate', true, '📱', 'cyan', 'website', 'domain', 'Meta', 'Self-paced', ARRAY['React Native', 'JavaScript', 'Mobile'], ARRAY['Developer'], 4.75, 4.70, 15000, 95, 14500),
('Swift Playgrounds', 'Learn Swift coding on iPad', 'https://www.apple.com/swift/playgrounds/', 'Mobile Development', 'beginner', true, '🍎', 'orange', 'course', 'domain', 'Apple', '20 hours', ARRAY['Swift', 'iOS', 'Apple'], ARRAY['Student', 'Beginner'], 4.7, 4.65, 8500, 94, 8200),
('Android Developers Guide', 'Official Android development documentation', 'https://developer.android.com/guide', 'Mobile Development', 'intermediate', true, '🤖', 'green', 'website', 'domain', 'Google', 'Self-paced', ARRAY['Android', 'Kotlin', 'Java'], ARRAY['Developer'], 4.8, 4.76, 22000, 96, 21500),
('iOS App Dev Tutorials', 'Apple official iOS development tutorials', 'https://developer.apple.com/tutorials/app-dev-training', 'Mobile Development', 'beginner', true, '📚', 'blue', 'course', 'domain', 'Apple', '15 hours', ARRAY['Swift', 'SwiftUI', 'iOS'], ARRAY['Developer', 'Student'], 4.85, 4.80, 12000, 97, 11800),
('The Complete Flutter Course', 'Comprehensive Flutter and Dart bootcamp', 'https://www.udemy.com/course/flutter-bootcamp-with-dart/', 'Mobile Development', 'beginner', false, '🎓', 'purple', 'course', 'domain', 'Udemy', '28 hours', ARRAY['Flutter', 'Dart', 'Firebase'], ARRAY['Student', 'Developer'], 4.75, 4.70, 45000, 95, 43000),
('Kotlin for Android', 'Kotlin language learning path', 'https://kotlinlang.org/docs/android-overview.html', 'Mobile Development', 'intermediate', true, '📖', 'purple', 'website', 'domain', 'JetBrains', 'Self-paced', ARRAY['Kotlin', 'Android', 'JVM'], ARRAY['Developer'], 4.7, 4.65, 9500, 94, 9200),
('Firebase Documentation', 'Backend services for mobile apps', 'https://firebase.google.com/docs', 'Mobile Development', 'intermediate', true, '🔥', 'orange', 'website', 'domain', 'Google', 'Self-paced', ARRAY['Firebase', 'Backend', 'Real-time'], ARRAY['Developer'], 4.8, 4.76, 18000, 96, 17500),
('Expo Documentation', 'Simplified React Native development', 'https://docs.expo.dev', 'Mobile Development', 'beginner', true, '📱', 'black', 'website', 'domain', 'Expo', 'Self-paced', ARRAY['Expo', 'React Native', 'Mobile'], ARRAY['Developer'], 4.7, 4.65, 8500, 94, 8200),
('SwiftUI Tutorials', 'Declarative UI framework for Apple platforms', 'https://developer.apple.com/tutorials/swiftui', 'Mobile Development', 'intermediate', true, '🎨', 'blue', 'course', 'domain', 'Apple', '10 hours', ARRAY['SwiftUI', 'Swift', 'iOS', 'macOS'], ARRAY['Developer'], 4.85, 4.80, 9500, 97, 9300),
('Flutter YouTube Channel', 'Official Flutter tutorials and updates', 'https://www.youtube.com/@flutterdev', 'Mobile Development', 'beginner', true, '🎬', 'blue', 'video', 'domain', 'Google', 'Self-paced', ARRAY['Flutter', 'Dart', 'UI'], ARRAY['Developer', 'Student'], 4.75, 4.70, 12000, 95, 11700),
('Mobile Design Patterns', 'Common mobile UI/UX patterns', 'https://mobbin.com/browse/ios/apps', 'Mobile Development', 'intermediate', true, '🎨', 'pink', 'website', 'domain', 'Mobbin', 'Self-paced', ARRAY['UI Design', 'UX', 'Mobile Patterns'], ARRAY['Designer', 'Developer'], 4.7, 4.65, 6500, 94, 6200),

-- UI/UX DESIGN RESOURCES (12)
('Figma Learn', 'Official Figma tutorials and courses', 'https://help.figma.com/hc/en-us/categories/360002051613-Get-started', 'UI/UX Design', 'beginner', true, '🎨', 'purple', 'course', 'domain', 'Figma', 'Self-paced', ARRAY['Figma', 'UI Design', 'Prototyping'], ARRAY['Designer', 'Student'], 4.9, 4.87, 35000, 98, 34000),
('Google UX Design Certificate', 'Professional UX certification from Google', 'https://www.coursera.org/professional-certificates/google-ux-design', 'UI/UX Design', 'beginner', false, '🎓', 'blue', 'certification', 'domain', 'Google', '6 months', ARRAY['UX Design', 'User Research', 'Prototyping'], ARRAY['Career Changer', 'Student'], 4.8, 4.76, 65000, 96, 62000),
('Laws of UX', 'Psychology principles for better design', 'https://lawsofux.com', 'UI/UX Design', 'intermediate', true, '📖', 'black', 'website', 'domain', 'Jon Yablonski', '2 hours', ARRAY['UX Psychology', 'Design Principles'], ARRAY['Designer'], 4.85, 4.80, 15000, 97, 14700),
('Refactoring UI', 'Design tips for developers', 'https://www.refactoringui.com', 'UI/UX Design', 'intermediate', false, '📕', 'teal', 'book', 'domain', 'Adam Wathan', '8 hours', ARRAY['UI Design', 'Visual Design'], ARRAY['Developer', 'Designer'], 4.9, 4.88, 18000, 99, 17800),
('Nielsen Norman Group', 'UX research and articles', 'https://www.nngroup.com/articles/', 'UI/UX Design', 'intermediate', true, '📰', 'blue', 'blog', 'domain', 'Nielsen Norman', 'Weekly', ARRAY['UX Research', 'Usability', 'Best Practices'], ARRAY['Designer', 'Researcher'], 4.85, 4.80, 22000, 97, 21500),
('Dribbble Learn', 'Design inspiration and learning resources', 'https://dribbble.com/learn', 'UI/UX Design', 'beginner', true, '🎨', 'pink', 'website', 'domain', 'Dribbble', 'Self-paced', ARRAY['UI Design', 'Inspiration', 'Portfolio'], ARRAY['Designer', 'Student'], 4.6, 4.55, 18000, 91, 17000),
('Design Systems Handbook', 'Building and maintaining design systems', 'https://www.designsystemschecklist.com', 'UI/UX Design', 'advanced', true, '📘', 'blue', 'website', 'domain', 'DesignBetter', '10 hours', ARRAY['Design Systems', 'Components', 'Tokens'], ARRAY['Designer', 'Developer'], 4.75, 4.70, 8500, 95, 8200),
('Interaction Design Foundation', 'Accredited UX design courses', 'https://www.interaction-design.org', 'UI/UX Design', 'intermediate', false, '🎓', 'green', 'course', 'domain', 'IDF', 'Self-paced', ARRAY['UX Design', 'Interaction Design', 'Research'], ARRAY['Designer'], 4.7, 4.65, 25000, 94, 24000),
('Don Norman Designs', 'Design thinking from the master', 'https://jnd.org', 'UI/UX Design', 'advanced', true, '📖', 'red', 'blog', 'domain', 'Don Norman', 'Weekly', ARRAY['Design Thinking', 'Human-Centered Design'], ARRAY['Designer', 'Researcher'], 4.8, 4.76, 9500, 96, 9200),
('Awwwards', 'Best web design inspiration', 'https://www.awwwards.com', 'UI/UX Design', 'intermediate', true, '🏆', 'black', 'website', 'domain', 'Awwwards', 'Daily', ARRAY['Web Design', 'Inspiration', 'Trends'], ARRAY['Designer', 'Developer'], 4.7, 4.65, 15000, 94, 14500),
('Sketch App Tutorials', 'Learn Sketch for UI design', 'https://www.sketch.com/docs/', 'UI/UX Design', 'beginner', true, '💎', 'orange', 'website', 'domain', 'Sketch', 'Self-paced', ARRAY['Sketch', 'UI Design', 'macOS'], ARRAY['Designer'], 4.6, 4.55, 8500, 91, 8200),
('UX Design Institute', 'University-certified UX diploma', 'https://www.uxdesigninstitute.com', 'UI/UX Design', 'beginner', false, '🎓', 'blue', 'certification', 'domain', 'UX Design Institute', '6 months', ARRAY['UX Design', 'User Research', 'Portfolio'], ARRAY['Career Changer'], 4.75, 4.70, 5500, 95, 5300),

-- BLOCKCHAIN RESOURCES (12)
('Ethereum.org Learn', 'Official Ethereum learning hub', 'https://ethereum.org/en/learn/', 'Blockchain', 'beginner', true, '⟠', 'purple', 'website', 'domain', 'Ethereum Foundation', 'Self-paced', ARRAY['Ethereum', 'Smart Contracts', 'Web3'], ARRAY['Developer', 'Student'], 4.85, 4.80, 25000, 97, 24500),
('CryptoZombies', 'Learn Solidity by building games', 'https://cryptozombies.io', 'Blockchain', 'beginner', true, '🧟', 'green', 'course', 'domain', 'Loom Network', '10 hours', ARRAY['Solidity', 'Ethereum', 'Smart Contracts'], ARRAY['Developer'], 4.9, 4.87, 45000, 98, 44000),
('Blockchain at Berkeley', 'University blockchain courses', 'https://blockchain.berkeley.edu/courses/', 'Blockchain', 'intermediate', true, '🎓', 'blue', 'course', 'domain', 'UC Berkeley', '20 hours', ARRAY['Blockchain', 'Bitcoin', 'Decentralization'], ARRAY['Student', 'Developer'], 4.75, 4.70, 12000, 95, 11700),
('Solidity Documentation', 'Official Solidity language docs', 'https://docs.soliditylang.org', 'Blockchain', 'intermediate', true, '📖', 'gray', 'website', 'domain', 'Ethereum', 'Self-paced', ARRAY['Solidity', 'EVM', 'Smart Contracts'], ARRAY['Developer'], 4.7, 4.65, 18000, 94, 17500),
('Web3 University', 'Free blockchain development courses', 'https://www.web3.university', 'Blockchain', 'beginner', true, '🌐', 'purple', 'course', 'domain', 'Alchemy', 'Self-paced', ARRAY['Web3', 'DApps', 'Ethereum'], ARRAY['Developer', 'Student'], 4.8, 4.76, 15000, 96, 14700),
('Buildspace', 'Project-based Web3 learning', 'https://buildspace.so', 'Blockchain', 'beginner', true, '🚀', 'black', 'course', 'domain', 'Buildspace', '2 weeks', ARRAY['NFTs', 'DAOs', 'Solidity'], ARRAY['Developer'], 4.85, 4.80, 28000, 97, 27500),
('Chainlink Docs', 'Decentralized oracle network', 'https://docs.chain.link', 'Blockchain', 'intermediate', true, '🔗', 'blue', 'website', 'domain', 'Chainlink', 'Self-paced', ARRAY['Chainlink', 'Oracles', 'Smart Contracts'], ARRAY['Developer'], 4.7, 4.65, 9500, 94, 9200),
('Mastering Bitcoin', 'Comprehensive Bitcoin technical book', 'https://github.com/bitcoinbook/bitcoinbook', 'Blockchain', 'advanced', true, '₿', 'orange', 'book', 'domain', 'Andreas Antonopoulos', '15 hours', ARRAY['Bitcoin', 'Cryptography', 'Protocol'], ARRAY['Developer', 'Researcher'], 4.9, 4.88, 22000, 99, 21800),
('Hardhat Documentation', 'Ethereum development environment', 'https://hardhat.org/docs', 'Blockchain', 'intermediate', true, '🔨', 'yellow', 'website', 'domain', 'Nomic Foundation', 'Self-paced', ARRAY['Hardhat', 'Solidity', 'Testing'], ARRAY['Developer'], 4.75, 4.70, 12000, 95, 11700),
('OpenZeppelin Docs', 'Secure smart contract library', 'https://docs.openzeppelin.com', 'Blockchain', 'intermediate', true, '🛡️', 'blue', 'website', 'domain', 'OpenZeppelin', 'Self-paced', ARRAY['Security', 'Smart Contracts', 'Standards'], ARRAY['Developer'], 4.8, 4.76, 15000, 96, 14700),
('The Graph Docs', 'Indexing protocol for Web3', 'https://thegraph.com/docs/en/', 'Blockchain', 'advanced', true, '📊', 'purple', 'website', 'domain', 'The Graph', 'Self-paced', ARRAY['The Graph', 'Subgraphs', 'Indexing'], ARRAY['Developer'], 4.7, 4.65, 6500, 94, 6300),
('Finematics YouTube', 'DeFi concepts explained visually', 'https://www.youtube.com/@Finematics', 'Blockchain', 'beginner', true, '🎬', 'green', 'video', 'domain', 'Finematics', 'Self-paced', ARRAY['DeFi', 'Yield Farming', 'Liquidity'], ARRAY['Investor', 'Developer'], 4.85, 4.80, 18000, 97, 17700),

-- DIGITAL MARKETING RESOURCES (12)
('Google Digital Garage', 'Free digital marketing courses from Google', 'https://learndigital.withgoogle.com/digitalgarage', 'Digital Marketing', 'beginner', true, '🎓', 'blue', 'course', 'domain', 'Google', '40 hours', ARRAY['Digital Marketing', 'SEO', 'Analytics'], ARRAY['Marketer', 'Student'], 4.8, 4.76, 85000, 96, 82000),
('HubSpot Academy', 'Free inbound marketing certification', 'https://academy.hubspot.com', 'Digital Marketing', 'beginner', true, '🎓', 'orange', 'certification', 'domain', 'HubSpot', '6 hours', ARRAY['Inbound Marketing', 'Content', 'Email'], ARRAY['Marketer'], 4.75, 4.70, 65000, 95, 62000),
('Moz SEO Learning Center', 'Comprehensive SEO guides', 'https://moz.com/learn/seo', 'Digital Marketing', 'intermediate', true, '📖', 'blue', 'website', 'domain', 'Moz', 'Self-paced', ARRAY['SEO', 'Keywords', 'Link Building'], ARRAY['Marketer', 'Content Creator'], 4.8, 4.76, 35000, 96, 34000),
('Google Analytics Academy', 'Official GA4 certification', 'https://skillshop.withgoogle.com/analytics', 'Digital Marketing', 'beginner', true, '📊', 'orange', 'certification', 'domain', 'Google', '10 hours', ARRAY['Analytics', 'GA4', 'Data Analysis'], ARRAY['Marketer', 'Analyst'], 4.7, 4.65, 55000, 94, 52000),
('Facebook Blueprint', 'Meta advertising certification', 'https://www.facebookblueprint.com', 'Digital Marketing', 'intermediate', true, '📘', 'blue', 'certification', 'domain', 'Meta', '15 hours', ARRAY['Facebook Ads', 'Instagram Ads', 'Social'], ARRAY['Marketer'], 4.65, 4.60, 42000, 93, 40000),
('Neil Patel Digital Marketing', 'Free marketing tools and guides', 'https://neilpatel.com', 'Digital Marketing', 'intermediate', true, '📰', 'orange', 'blog', 'domain', 'Neil Patel', 'Weekly', ARRAY['SEO', 'Content Marketing', 'Growth'], ARRAY['Marketer', 'Entrepreneur'], 4.7, 4.65, 28000, 94, 27000),
('Ahrefs Academy', 'SEO and content marketing courses', 'https://ahrefs.com/academy', 'Digital Marketing', 'intermediate', true, '🎓', 'blue', 'course', 'domain', 'Ahrefs', '10 hours', ARRAY['SEO', 'Backlinks', 'Keyword Research'], ARRAY['Marketer', 'SEO Specialist'], 4.8, 4.76, 18000, 96, 17500),
('Copyblogger', 'Content marketing and copywriting', 'https://copyblogger.com', 'Digital Marketing', 'intermediate', true, '✍️', 'black', 'blog', 'domain', 'Copyblogger', 'Weekly', ARRAY['Copywriting', 'Content Strategy'], ARRAY['Content Creator', 'Marketer'], 4.7, 4.65, 15000, 94, 14500),
('Semrush Academy', 'Free SEO and marketing courses', 'https://www.semrush.com/academy/', 'Digital Marketing', 'beginner', true, '🎓', 'orange', 'course', 'domain', 'Semrush', 'Self-paced', ARRAY['SEO', 'PPC', 'Content Marketing'], ARRAY['Marketer'], 4.75, 4.70, 22000, 95, 21500),
('Marketing Over Coffee', 'Marketing podcast and resources', 'https://www.marketingovercoffee.com', 'Digital Marketing', 'beginner', true, '☕', 'brown', 'video', 'domain', 'Marketing Over Coffee', 'Weekly', ARRAY['Marketing News', 'Strategy', 'Tips'], ARRAY['Marketer'], 4.6, 4.55, 8500, 91, 8200),
('Buffer Resources', 'Social media marketing guides', 'https://buffer.com/resources/', 'Digital Marketing', 'beginner', true, '📱', 'blue', 'blog', 'domain', 'Buffer', 'Weekly', ARRAY['Social Media', 'Scheduling', 'Analytics'], ARRAY['Social Media Manager'], 4.7, 4.65, 12000, 94, 11700),
('Content Marketing Institute', 'Strategic content marketing', 'https://contentmarketinginstitute.com', 'Digital Marketing', 'intermediate', true, '📰', 'orange', 'blog', 'domain', 'CMI', 'Weekly', ARRAY['Content Strategy', 'B2B Marketing'], ARRAY['Content Marketer'], 4.75, 4.70, 15000, 95, 14700);
