
-- BATCH 1: Fine Arts & Visual Arts Resources
INSERT INTO resources (title, description, link, category, difficulty, resource_type, section_type, icon, color, is_free, provider, duration, related_skills, relevant_backgrounds, is_active, is_featured)
VALUES
-- Fine Arts Courses
('The Complete Drawing Masterclass', 'Learn drawing from absolute beginner to advanced. Covers pencil, charcoal, ink and more with 100+ exercises.', 'https://www.udemy.com/course/the-complete-drawing-masterclass-course/', 'Fine Arts', 'beginner', 'course', 'domain', '🎨', 'pink', false, 'Udemy', '30 hours', ARRAY['drawing', 'sketching', 'shading', 'perspective'], ARRAY['visual-arts', 'creative'], true, true),
('Fundamentals of Drawing - Proko', 'Anatomy and figure drawing fundamentals taught by professional artist Stan Prokopenko.', 'https://www.proko.com/course/fundamentals-of-drawing/', 'Fine Arts', 'beginner', 'course', 'domain', '🎨', 'pink', false, 'Proko', '15 hours', ARRAY['figure drawing', 'anatomy', 'gesture drawing'], ARRAY['visual-arts'], true, false),
('Watercolor Painting for Beginners - Skillshare', 'Master watercolor techniques including wet-on-wet, layering, and color mixing.', 'https://www.skillshare.com/classes/Watercolor-Painting-for-Beginners/', 'Fine Arts', 'beginner', 'course', 'domain', '🎨', 'pink', false, 'Skillshare', '3 hours', ARRAY['watercolor', 'painting', 'color theory'], ARRAY['visual-arts'], true, false),
('Oil Painting Essentials - New Masters Academy', 'Classical oil painting techniques from professional artists covering alla prima, glazing, and composition.', 'https://www.nma.art/courses/oil-painting-essentials/', 'Fine Arts', 'intermediate', 'course', 'domain', '🎨', 'pink', false, 'New Masters Academy', '25 hours', ARRAY['oil painting', 'color mixing', 'composition'], ARRAY['visual-arts'], true, true),
('Digital Art for Beginners - Domestika', 'Create stunning digital illustrations using Procreate and Photoshop from scratch.', 'https://www.domestika.org/en/courses/digital-art-beginners', 'Fine Arts', 'beginner', 'course', 'domain', '🎨', 'pink', false, 'Domestika', '8 hours', ARRAY['digital art', 'procreate', 'illustration'], ARRAY['visual-arts', 'digital-design'], true, false),
('Sculpture Fundamentals - The Great Courses', 'Introduction to 3D sculptural forms using clay, wire, and mixed media.', 'https://www.thegreatcourses.com/courses/how-to-draw-and-paint', 'Fine Arts', 'beginner', 'course', 'domain', '🎨', 'pink', false, 'The Great Courses', '12 hours', ARRAY['sculpture', 'clay', '3d art'], ARRAY['visual-arts'], true, false),
('Portrait Drawing - Watts Atelier', 'Learn classical portrait drawing techniques used by professional portrait artists.', 'https://www.wattsatelier.com/portrait-drawing', 'Fine Arts', 'intermediate', 'course', 'domain', '🎨', 'pink', false, 'Watts Atelier', '20 hours', ARRAY['portrait', 'charcoal', 'likeness'], ARRAY['visual-arts'], true, false),
('Abstract Art: Acrylic Painting Techniques', 'Explore abstract expressionism with acrylic paints, palette knives, and mixed media.', 'https://www.udemy.com/course/abstract-art-acrylic-painting/', 'Fine Arts', 'intermediate', 'course', 'domain', '🎨', 'pink', false, 'Udemy', '10 hours', ARRAY['abstract art', 'acrylic', 'mixed media'], ARRAY['visual-arts'], true, false),
('Art History: Renaissance to Modern - Coursera', 'Survey of Western art history from the Renaissance through contemporary movements.', 'https://www.coursera.org/learn/modern-art', 'Fine Arts', 'beginner', 'course', 'domain', '🎨', 'pink', true, 'Coursera / MoMA', '20 hours', ARRAY['art history', 'renaissance', 'modern art'], ARRAY['visual-arts', 'humanities'], true, true),
('Printmaking Techniques - London Art College', 'Linocut, etching, screen printing and monoprint techniques for beginners.', 'https://www.londonartcollege.co.uk/courses/printmaking', 'Fine Arts', 'beginner', 'course', 'domain', '🎨', 'pink', false, 'London Art College', '16 hours', ARRAY['printmaking', 'linocut', 'etching'], ARRAY['visual-arts'], true, false),

-- Graphic Design
('Graphic Design Specialization - CalArts', 'Complete graphic design program covering typography, imagemaking, and branding by CalArts.', 'https://www.coursera.org/specializations/graphic-design', 'Graphic Design', 'beginner', 'course', 'domain', '🖌️', 'indigo', true, 'Coursera / CalArts', '6 months', ARRAY['typography', 'branding', 'layout', 'color theory'], ARRAY['visual-arts', 'digital-design'], true, true),
('Adobe Illustrator CC – Complete Masterclass', 'Master vector graphics with Adobe Illustrator from logos to complex illustrations.', 'https://www.udemy.com/course/adobe-illustrator-cc-tutorial/', 'Graphic Design', 'beginner', 'course', 'domain', '🖌️', 'indigo', false, 'Udemy', '15 hours', ARRAY['illustrator', 'vector art', 'logo design'], ARRAY['digital-design'], true, false),
('Canva Design School', 'Free design tutorials covering social media graphics, presentations, and brand kits.', 'https://www.canva.com/designschool/', 'Graphic Design', 'beginner', 'course', 'domain', '🖌️', 'indigo', true, 'Canva', 'Self-paced', ARRAY['canva', 'social media design', 'branding'], ARRAY['digital-design', 'marketing'], true, false),
('Logo Design Masterclass - Domestika', 'Create memorable brand identities and logos from concept to final delivery.', 'https://www.domestika.org/en/courses/logo-design', 'Graphic Design', 'intermediate', 'course', 'domain', '🖌️', 'indigo', false, 'Domestika', '6 hours', ARRAY['logo design', 'branding', 'identity'], ARRAY['digital-design'], true, false),
('Color Theory for Designers', 'Deep dive into color psychology, harmonies, and practical application in design projects.', 'https://www.interaction-design.org/courses/color-for-designers', 'Graphic Design', 'beginner', 'course', 'domain', '🖌️', 'indigo', false, 'IxDF', '8 hours', ARRAY['color theory', 'visual hierarchy', 'design principles'], ARRAY['digital-design'], true, false),

-- Photography
('Photography Masterclass - Complete Guide', 'From camera settings to post-processing: DSLR, mirrorless, and smartphone photography.', 'https://www.udemy.com/course/photography-masterclass-complete-guide-to-photography/', 'Photography', 'beginner', 'course', 'domain', '📷', 'teal', false, 'Udemy', '25 hours', ARRAY['photography', 'composition', 'lighting', 'editing'], ARRAY['photography', 'visual-arts'], true, true),
('iPhone Photography - Apple Creative Studios', 'Master iPhone camera features, portrait mode, and mobile editing workflows.', 'https://www.apple.com/today/collection/photo-and-video/', 'Photography', 'beginner', 'course', 'domain', '📷', 'teal', true, 'Apple', '5 hours', ARRAY['mobile photography', 'iphone', 'editing'], ARRAY['photography'], true, false),
('Adobe Lightroom CC Photo Editing Masterclass', 'Complete Lightroom workflow from import to export with professional color grading.', 'https://www.udemy.com/course/adobe-lightroom-cc-photo-editing-masterclass/', 'Photography', 'intermediate', 'course', 'domain', '📷', 'teal', false, 'Udemy', '12 hours', ARRAY['lightroom', 'photo editing', 'color grading'], ARRAY['photography'], true, false),
('Street Photography: Capture Life - Magnum Photos', 'Learn street photography from Magnum Photos members covering composition and storytelling.', 'https://www.magnumphotos.com/learn/', 'Photography', 'intermediate', 'course', 'domain', '📷', 'teal', false, 'Magnum Photos', '10 hours', ARRAY['street photography', 'documentary', 'storytelling'], ARRAY['photography'], true, true),
('Night Photography & Light Painting', 'Master long exposure, astrophotography, and creative light painting techniques.', 'https://www.skillshare.com/classes/Night-Photography/', 'Photography', 'advanced', 'course', 'domain', '📷', 'teal', false, 'Skillshare', '4 hours', ARRAY['night photography', 'long exposure', 'astrophotography'], ARRAY['photography'], true, false),

-- Animation
('The Animator''s Survival Kit - Online Course', 'Based on Richard Williams'' legendary book, covering walk cycles, timing and spacing.', 'https://www.animatorsurvivalkit.com/', 'Animation', 'intermediate', 'course', 'domain', '🎞️', 'fuchsia', false, 'Richard Williams', '16 hours', ARRAY['2d animation', 'walk cycle', 'timing'], ARRAY['animation', 'visual-arts'], true, true),
('Blender 3D Character Creation', 'Create and rig 3D characters in Blender from modeling to animation.', 'https://www.udemy.com/course/blender-character-creator-v2/', 'Animation', 'intermediate', 'course', 'domain', '🎞️', 'fuchsia', false, 'Udemy', '40 hours', ARRAY['blender', '3d modeling', 'rigging', 'character design'], ARRAY['animation', '3d-art'], true, false),
('Pixel Art Masterclass - Udemy', 'Create retro game pixel art characters, environments and animations.', 'https://www.udemy.com/course/pixel-art-master-course/', 'Animation', 'beginner', 'course', 'domain', '🎞️', 'fuchsia', false, 'Udemy', '8 hours', ARRAY['pixel art', 'game art', 'sprite animation'], ARRAY['animation', 'game-dev'], true, false),

-- Fashion Design
('Fashion Design: Start to Finish - Coursera', 'Learn fashion design fundamentals from sketching to garment construction.', 'https://www.coursera.org/learn/fashion-design', 'Fashion Design', 'beginner', 'course', 'domain', '👗', 'rose', true, 'Coursera', '20 hours', ARRAY['fashion illustration', 'pattern making', 'textiles'], ARRAY['fashion', 'creative'], true, true),
('Sewing Machine Mastery', 'From threading to advanced techniques: complete sewing machine guide.', 'https://www.craftsy.com/class/sewing-machine-mastery/', 'Fashion Design', 'beginner', 'course', 'domain', '👗', 'rose', false, 'Craftsy', '6 hours', ARRAY['sewing', 'garment construction', 'textiles'], ARRAY['fashion'], true, false),
('Fashion Illustration with Adobe Illustrator', 'Create professional fashion flats and technical drawings digitally.', 'https://www.skillshare.com/classes/Fashion-Illustration/', 'Fashion Design', 'intermediate', 'course', 'domain', '👗', 'rose', false, 'Skillshare', '5 hours', ARRAY['fashion illustration', 'adobe illustrator', 'tech packs'], ARRAY['fashion', 'digital-design'], true, false),

-- Interior Design
('Interior Design Fundamentals - Skillshare', 'Room layout, color schemes, furniture selection and space planning basics.', 'https://www.skillshare.com/classes/Interior-Design-Fundamentals/', 'Interior Design', 'beginner', 'course', 'domain', '🏠', 'amber', false, 'Skillshare', '8 hours', ARRAY['space planning', 'color schemes', 'furniture'], ARRAY['interior-design', 'creative'], true, true),
('SketchUp for Interior Design', 'Create 3D interior visualizations and floor plans with SketchUp.', 'https://www.udemy.com/course/sketchup-for-interior-design/', 'Interior Design', 'intermediate', 'course', 'domain', '🏠', 'amber', false, 'Udemy', '12 hours', ARRAY['sketchup', '3d visualization', 'floor plans'], ARRAY['interior-design', 'architecture'], true, false)

ON CONFLICT DO NOTHING;
