
-- BATCH 2: Finance, Business, Music, Writing, and more
INSERT INTO resources (title, description, link, category, difficulty, resource_type, section_type, icon, color, is_free, provider, duration, related_skills, relevant_backgrounds, is_active, is_featured)
VALUES
-- Finance & Investment
('Financial Markets - Yale (Robert Shiller)', 'Nobel laureate Robert Shiller teaches financial markets, risk management, and behavioral finance.', 'https://www.coursera.org/learn/financial-markets-global', 'Finance', 'beginner', 'course', 'domain', '💰', 'green', true, 'Coursera / Yale', '33 hours', ARRAY['financial markets', 'risk management', 'behavioral finance'], ARRAY['finance', 'economics'], true, true),
('CFA Level 1 Complete Preparation', 'Comprehensive CFA Level 1 exam prep covering ethics, quant, economics, and portfolio management.', 'https://www.kaplanfinancial.com/cfa/level-1', 'Finance', 'advanced', 'certification', 'domain', '📊', 'green', false, 'Kaplan', '300+ hours', ARRAY['cfa', 'financial analysis', 'portfolio management'], ARRAY['finance'], true, true),
('Personal Finance 101 - Khan Academy', 'Free personal finance education: budgeting, saving, investing, taxes and retirement.', 'https://www.khanacademy.org/college-careers-more/personal-finance', 'Finance', 'beginner', 'course', 'domain', '💰', 'green', true, 'Khan Academy', '15 hours', ARRAY['budgeting', 'investing', 'retirement', 'taxes'], ARRAY['finance', 'general'], true, false),
('Stock Market Investing for Beginners', 'Learn stock analysis, portfolio building, and investment strategies from scratch.', 'https://www.udemy.com/course/stock-market-investing/', 'Investment', 'beginner', 'course', 'domain', '📈', 'green', false, 'Udemy', '12 hours', ARRAY['stocks', 'portfolio', 'fundamental analysis'], ARRAY['finance', 'investment'], true, false),
('Financial Modeling & Valuation - Wall Street Prep', 'Build financial models and perform DCF valuations used by investment banks.', 'https://www.wallstreetprep.com/self-study-programs/financial-modeling/', 'Finance', 'advanced', 'course', 'domain', '📊', 'green', false, 'Wall Street Prep', '40 hours', ARRAY['financial modeling', 'dcf', 'valuation', 'excel'], ARRAY['finance', 'investment-banking'], true, true),
('Cryptocurrency & Blockchain - MIT', 'MIT professor Gary Gensler teaches blockchain technology, crypto economics and regulation.', 'https://ocw.mit.edu/courses/15-s12-blockchain-and-money-fall-2018/', 'Finance', 'intermediate', 'course', 'domain', '💰', 'green', true, 'MIT OpenCourseWare', '24 hours', ARRAY['cryptocurrency', 'blockchain', 'defi'], ARRAY['finance', 'technology'], true, false),
('Accounting Fundamentals - edX', 'Introduction to financial accounting: balance sheets, income statements and cash flows.', 'https://www.edx.org/learn/accounting', 'Accounting', 'beginner', 'course', 'domain', '📊', 'emerald', true, 'edX', '20 hours', ARRAY['accounting', 'financial statements', 'bookkeeping'], ARRAY['finance', 'accounting'], true, false),
('Tax Preparation & Planning Course', 'Learn tax filing, deductions, credits and planning strategies for individuals and small businesses.', 'https://www.udemy.com/course/tax-preparation/', 'Accounting', 'intermediate', 'course', 'domain', '📊', 'emerald', false, 'Udemy', '10 hours', ARRAY['tax preparation', 'tax planning', 'deductions'], ARRAY['accounting', 'finance'], true, false),
('Excel for Financial Analysis', 'Master Excel formulas, pivot tables, charts and financial functions for business analysis.', 'https://www.udemy.com/course/excel-for-financial-analysis/', 'Finance', 'intermediate', 'course', 'domain', '📊', 'green', false, 'Udemy', '14 hours', ARRAY['excel', 'financial analysis', 'pivot tables', 'vlookup'], ARRAY['finance', 'business'], true, false),
('Real Estate Investing Masterclass', 'Rental properties, REITs, flipping and commercial real estate investment strategies.', 'https://www.udemy.com/course/real-estate-investing-masterclass/', 'Investment', 'intermediate', 'course', 'domain', '📈', 'green', false, 'Udemy', '18 hours', ARRAY['real estate', 'rental income', 'reits'], ARRAY['investment', 'finance'], true, false),

-- Music
('Music Theory Fundamentals - Berklee', 'Berklee College of Music teaches scales, chords, rhythm, and harmony from scratch.', 'https://www.coursera.org/learn/music-theory', 'Music', 'beginner', 'course', 'domain', '🎵', 'purple', true, 'Coursera / Berklee', '20 hours', ARRAY['music theory', 'scales', 'chords', 'harmony'], ARRAY['music'], true, true),
('Complete Guitar Lessons System - Beginner to Advanced', 'Acoustic and electric guitar from first chords to advanced soloing and fingerpicking.', 'https://www.udemy.com/course/complete-guitar-system-beginner-to-advanced/', 'Music', 'beginner', 'course', 'domain', '🎵', 'purple', false, 'Udemy', '35 hours', ARRAY['guitar', 'chords', 'fingerpicking', 'music theory'], ARRAY['music'], true, true),
('Music Production in Ableton Live - Berklee', 'Create, produce and mix music using Ableton Live from Berklee instructors.', 'https://www.coursera.org/specializations/music-production', 'Music', 'intermediate', 'course', 'domain', '🎵', 'purple', true, 'Coursera / Berklee', '4 months', ARRAY['ableton', 'music production', 'mixing', 'mastering'], ARRAY['music', 'audio-engineering'], true, true),
('Piano for Beginners - flowkey', 'Interactive piano lessons with real-time feedback, popular songs and classical pieces.', 'https://www.flowkey.com/', 'Music', 'beginner', 'course', 'domain', '🎵', 'purple', false, 'flowkey', 'Self-paced', ARRAY['piano', 'sight reading', 'music theory'], ARRAY['music'], true, false),
('Songwriting: Writing the Lyrics - Berklee', 'Craft compelling song lyrics covering structure, rhyme schemes and storytelling.', 'https://www.coursera.org/learn/songwriting-lyrics', 'Music', 'intermediate', 'course', 'domain', '🎵', 'purple', true, 'Coursera / Berklee', '15 hours', ARRAY['songwriting', 'lyrics', 'creative writing'], ARRAY['music', 'creative-writing'], true, false),
('FL Studio Complete Masterclass', 'Beat making, mixing and mastering in FL Studio for hip-hop, EDM and pop production.', 'https://www.udemy.com/course/fl-studio-masterclass/', 'Music', 'beginner', 'course', 'domain', '🎵', 'purple', false, 'Udemy', '20 hours', ARRAY['fl studio', 'beat making', 'mixing'], ARRAY['music', 'audio-engineering'], true, false),
('Singing Success - Vocal Training', 'Improve vocal range, breath control, and performance technique with structured exercises.', 'https://www.singingsuccess.com/', 'Music', 'beginner', 'course', 'domain', '🎵', 'purple', false, 'Singing Success', '12 hours', ARRAY['vocals', 'singing', 'breath control'], ARRAY['music'], true, false),

-- Creative Writing
('Creative Writing Specialization - Wesleyan', 'Covers plot, character, setting, style and the complete writing workshop process.', 'https://www.coursera.org/specializations/creative-writing', 'Creative Writing', 'beginner', 'course', 'domain', '✍️', 'orange', true, 'Coursera / Wesleyan', '6 months', ARRAY['fiction writing', 'plot', 'character development'], ARRAY['creative-writing', 'humanities'], true, true),
('MasterClass: Neil Gaiman Teaches Storytelling', 'Award-winning author Neil Gaiman shares his approach to crafting compelling stories.', 'https://www.masterclass.com/classes/neil-gaiman-teaches-the-art-of-storytelling', 'Creative Writing', 'intermediate', 'course', 'domain', '✍️', 'orange', false, 'MasterClass', '5 hours', ARRAY['storytelling', 'fiction', 'world building'], ARRAY['creative-writing'], true, true),
('Screenwriting 101 - ScreenCraft', 'Write your first screenplay: structure, dialogue, character arcs and formatting.', 'https://screencraft.org/courses/', 'Creative Writing', 'beginner', 'course', 'domain', '✍️', 'orange', false, 'ScreenCraft', '10 hours', ARRAY['screenwriting', 'dialogue', 'story structure'], ARRAY['creative-writing', 'film'], true, false),
('Poetry Writing - Coursera', 'Explore poetic forms, imagery, meter and revision with published poets.', 'https://www.coursera.org/learn/poetry-writing', 'Creative Writing', 'intermediate', 'course', 'domain', '✍️', 'orange', true, 'Coursera', '12 hours', ARRAY['poetry', 'imagery', 'meter', 'revision'], ARRAY['creative-writing'], true, false),
('Copywriting Secrets - How to Write Copy That Sells', 'Direct response copywriting for sales pages, emails, and ads.', 'https://www.udemy.com/course/copywriting-secrets/', 'Creative Writing', 'intermediate', 'course', 'domain', '✍️', 'orange', false, 'Udemy', '8 hours', ARRAY['copywriting', 'sales copy', 'email marketing'], ARRAY['creative-writing', 'marketing'], true, false),
('Technical Writing - Google', 'Free technical writing courses by Google covering clarity, structure and documentation.', 'https://developers.google.com/tech-writing', 'Creative Writing', 'beginner', 'course', 'domain', '✍️', 'orange', true, 'Google', '6 hours', ARRAY['technical writing', 'documentation', 'clarity'], ARRAY['creative-writing', 'technology'], true, false),

-- Film & Video
('Filmmaking Specialization - Michigan State', 'Complete filmmaking from pre-production to post: directing, cinematography, and editing.', 'https://www.coursera.org/specializations/filmmaking', 'Film & Video', 'beginner', 'course', 'domain', '🎬', 'red', true, 'Coursera / MSU', '6 months', ARRAY['directing', 'cinematography', 'film editing'], ARRAY['film', 'visual-arts'], true, true),
('Adobe Premiere Pro Complete Course', 'Professional video editing in Premiere Pro from basics to advanced color grading.', 'https://www.udemy.com/course/adobe-premiere-pro-video-editing/', 'Film & Video', 'beginner', 'course', 'domain', '🎬', 'red', false, 'Udemy', '20 hours', ARRAY['premiere pro', 'video editing', 'color grading'], ARRAY['film', 'video'], true, false),
('DaVinci Resolve - Complete Video Editing Course', 'Free professional video editing software mastery: cut, color, fairlight and fusion.', 'https://www.udemy.com/course/davinci-resolve-video-editing/', 'Film & Video', 'beginner', 'course', 'domain', '🎬', 'red', false, 'Udemy', '25 hours', ARRAY['davinci resolve', 'color grading', 'video editing'], ARRAY['film', 'video'], true, true),
('Documentary Filmmaking - National Geographic', 'Storytelling techniques for documentary film from concept to distribution.', 'https://www.masterclass.com/classes/ken-burns-teaches-documentary-filmmaking', 'Film & Video', 'intermediate', 'course', 'domain', '🎬', 'red', false, 'MasterClass', '5 hours', ARRAY['documentary', 'storytelling', 'interviewing'], ARRAY['film', 'journalism'], true, false),
('YouTube Creator Academy', 'Official YouTube guide to growing a channel: content strategy, thumbnails, and monetization.', 'https://creatoracademy.youtube.com/', 'Film & Video', 'beginner', 'course', 'domain', '🎬', 'red', true, 'YouTube', 'Self-paced', ARRAY['youtube', 'content creation', 'video production'], ARRAY['video', 'marketing'], true, false),

-- Psychology
('Introduction to Psychology - Yale', 'Comprehensive intro to psychology by Professor Paul Bloom covering cognition, emotion, and social behavior.', 'https://www.coursera.org/learn/introduction-psychology', 'Psychology', 'beginner', 'course', 'domain', '🧠', 'violet', true, 'Coursera / Yale', '15 hours', ARRAY['psychology', 'cognition', 'behavior', 'emotions'], ARRAY['psychology', 'social-science'], true, true),
('Positive Psychology - UPenn', 'Martin Seligman teaches the science of well-being, resilience and flourishing.', 'https://www.coursera.org/learn/positive-psychology', 'Psychology', 'beginner', 'course', 'domain', '🧠', 'violet', true, 'Coursera / UPenn', '20 hours', ARRAY['positive psychology', 'well-being', 'resilience'], ARRAY['psychology'], true, false),
('CBT Techniques for Anxiety & Depression', 'Cognitive behavioral therapy techniques for managing anxiety and depression.', 'https://www.udemy.com/course/cbt-cognitive-behavioral-therapy/', 'Psychology', 'intermediate', 'course', 'domain', '🧠', 'violet', false, 'Udemy', '10 hours', ARRAY['cbt', 'anxiety', 'depression', 'therapy'], ARRAY['psychology', 'mental-health'], true, false),

-- Culinary Arts
('Culinary Arts & Sciences - Le Cordon Bleu', 'Cooking fundamentals from Le Cordon Bleu: knife skills, sauces, and French techniques.', 'https://www.cordonbleu.edu/programmes/culinary-arts', 'Culinary Arts', 'beginner', 'course', 'domain', '🍳', 'yellow', false, 'Le Cordon Bleu', '6 months', ARRAY['cooking', 'french cuisine', 'knife skills', 'sauces'], ARRAY['culinary', 'hospitality'], true, true),
('Baking Science - King Arthur Flour', 'Science of baking: bread, pastry, and cake techniques with precise measurement.', 'https://www.kingarthurbaking.com/learn', 'Culinary Arts', 'beginner', 'course', 'domain', '🍳', 'yellow', true, 'King Arthur', 'Self-paced', ARRAY['baking', 'bread', 'pastry'], ARRAY['culinary'], true, false),
('MasterClass: Gordon Ramsay Teaches Cooking', 'Learn restaurant-quality cooking from Gordon Ramsay: proteins, vegetables, pasta and more.', 'https://www.masterclass.com/classes/gordon-ramsay-teaches-cooking', 'Culinary Arts', 'intermediate', 'course', 'domain', '🍳', 'yellow', false, 'MasterClass', '5 hours', ARRAY['cooking', 'restaurant techniques', 'plating'], ARRAY['culinary'], true, true),
('Food Photography & Styling', 'Capture mouth-watering food photos: lighting, composition, and styling techniques.', 'https://www.skillshare.com/classes/Food-Photography/', 'Culinary Arts', 'intermediate', 'course', 'domain', '🍳', 'yellow', false, 'Skillshare', '4 hours', ARRAY['food photography', 'styling', 'lighting'], ARRAY['culinary', 'photography'], true, false),

-- Architecture
('Architectural Design - MIT OpenCourseWare', 'Fundamentals of architectural design thinking, spatial composition, and form.', 'https://ocw.mit.edu/courses/4-105-geometric-disciplines/', 'Architecture', 'intermediate', 'course', 'domain', '🏛️', 'stone', true, 'MIT OpenCourseWare', '30 hours', ARRAY['architectural design', 'spatial composition', 'form'], ARRAY['architecture'], true, true),
('AutoCAD Complete Course - Beginner to Advanced', 'Master AutoCAD for architectural and engineering 2D/3D drafting.', 'https://www.udemy.com/course/autocad-complete-course/', 'Architecture', 'beginner', 'course', 'domain', '🏛️', 'stone', false, 'Udemy', '20 hours', ARRAY['autocad', 'drafting', '2d drawing', '3d modeling'], ARRAY['architecture', 'engineering'], true, false),
('Revit Architecture Essentials', 'BIM fundamentals with Autodesk Revit for building design and documentation.', 'https://www.udemy.com/course/revit-architecture-essentials/', 'Architecture', 'intermediate', 'course', 'domain', '🏛️', 'stone', false, 'Udemy', '15 hours', ARRAY['revit', 'bim', 'building design'], ARRAY['architecture'], true, false),

-- Health & Fitness
('Nutrition Science - Stanford', 'Evidence-based nutrition: macronutrients, micronutrients, and diet planning.', 'https://www.coursera.org/learn/stanford-introduction-food-and-health', 'Health & Fitness', 'beginner', 'course', 'domain', '💪', 'lime', true, 'Coursera / Stanford', '10 hours', ARRAY['nutrition', 'diet', 'macronutrients', 'health'], ARRAY['health', 'fitness'], true, true),
('NASM Certified Personal Trainer Prep', 'Complete preparation for the NASM-CPT certification exam.', 'https://www.nasm.org/certified-personal-trainer', 'Health & Fitness', 'intermediate', 'certification', 'domain', '💪', 'lime', false, 'NASM', '3 months', ARRAY['personal training', 'exercise science', 'anatomy'], ARRAY['fitness', 'health'], true, true),
('Yoga for Beginners - Yoga with Adriene', 'Free yoga practice series covering 30 days of foundational yoga poses and flows.', 'https://www.youtube.com/playlist?list=PLui6Eyny-UzzWwJ4FdxI_OFFICIAL', 'Health & Fitness', 'beginner', 'course', 'domain', '💪', 'lime', true, 'YouTube', '15 hours', ARRAY['yoga', 'flexibility', 'mindfulness'], ARRAY['fitness', 'wellness'], true, false),

-- Law
('Introduction to American Law - UPenn', 'Overview of the US legal system: constitutional, criminal, tort and contract law.', 'https://www.coursera.org/learn/american-law', 'Law', 'beginner', 'course', 'domain', '⚖️', 'neutral', true, 'Coursera / UPenn', '16 hours', ARRAY['constitutional law', 'criminal law', 'contracts'], ARRAY['law', 'political-science'], true, true),
('Contract Law Fundamentals', 'Understanding contracts, agreements, negotiations and legal obligations.', 'https://www.edx.org/learn/contract-law', 'Law', 'intermediate', 'course', 'domain', '⚖️', 'neutral', true, 'edX', '12 hours', ARRAY['contracts', 'negotiation', 'legal writing'], ARRAY['law', 'business'], true, false),

-- Environmental Science
('Environmental Science - MIT', 'Climate change, ecosystems, pollution and sustainability from MIT faculty.', 'https://ocw.mit.edu/courses/12-001-introduction-to-geology-fall-2013/', 'Environmental Science', 'beginner', 'course', 'domain', '🌿', 'green', true, 'MIT OpenCourseWare', '20 hours', ARRAY['climate change', 'ecology', 'sustainability'], ARRAY['environmental-science', 'science'], true, true),
('Sustainability and Development - Columbia', 'Sustainable development goals, economics and policy from Jeffrey Sachs.', 'https://www.coursera.org/learn/sustainability', 'Environmental Science', 'intermediate', 'course', 'domain', '🌿', 'green', true, 'Coursera / Columbia', '15 hours', ARRAY['sustainability', 'sdgs', 'development'], ARRAY['environmental-science'], true, false),

-- Journalism
('Journalism for Social Change - UC Berkeley', 'Investigative journalism techniques, ethics and digital storytelling.', 'https://www.edx.org/learn/journalism', 'Journalism', 'beginner', 'course', 'domain', '📰', 'zinc', true, 'edX / UC Berkeley', '12 hours', ARRAY['investigative journalism', 'ethics', 'digital storytelling'], ARRAY['journalism', 'media'], true, true),
('Photojournalism & Documentary Photography', 'Tell powerful stories through photojournalism with ethical considerations.', 'https://www.coursera.org/learn/photography', 'Journalism', 'intermediate', 'course', 'domain', '📰', 'zinc', true, 'Coursera', '10 hours', ARRAY['photojournalism', 'documentary', 'ethics'], ARRAY['journalism', 'photography'], true, false),

-- Education
('Learning How to Learn - McMaster University', 'The world''s most popular online course on effective learning techniques and memory.', 'https://www.coursera.org/learn/learning-how-to-learn', 'Education', 'beginner', 'course', 'domain', '📚', 'sky', true, 'Coursera / McMaster', '15 hours', ARRAY['learning techniques', 'memory', 'study skills'], ARRAY['education', 'general'], true, true),
('Foundations of Teaching - Commonwealth Education Trust', 'Pedagogy, lesson planning, and classroom management for aspiring teachers.', 'https://www.coursera.org/learn/teaching', 'Education', 'beginner', 'course', 'domain', '📚', 'sky', true, 'Coursera', '20 hours', ARRAY['teaching', 'pedagogy', 'lesson planning'], ARRAY['education'], true, false),

-- Philosophy
('Introduction to Philosophy - University of Edinburgh', 'Explore fundamental philosophical questions: existence, knowledge, ethics, and mind.', 'https://www.coursera.org/learn/philosophy', 'Philosophy', 'beginner', 'course', 'domain', '💭', 'slate', true, 'Coursera / Edinburgh', '15 hours', ARRAY['ethics', 'metaphysics', 'epistemology', 'logic'], ARRAY['philosophy', 'humanities'], true, true),
('Ethics in Technology - Stanford', 'Philosophical examination of AI ethics, privacy, surveillance and digital rights.', 'https://www.coursera.org/learn/ethics-technology', 'Philosophy', 'intermediate', 'course', 'domain', '💭', 'slate', true, 'Coursera / Stanford', '10 hours', ARRAY['ai ethics', 'privacy', 'digital rights'], ARRAY['philosophy', 'technology'], true, false)

ON CONFLICT DO NOTHING;
