
-- ==================== EXAM: SAT (12 new) ====================
INSERT INTO resources (title, description, link, category, difficulty, is_free, resource_type, section_type, provider, duration, is_active, is_featured, related_skills, education_levels) VALUES
('Khan Academy SAT Prep', 'Official College Board partnership - personalized SAT practice with full-length tests', 'https://www.khanacademy.org/sat', 'SAT', 'intermediate', true, 'course', 'exam', 'Khan Academy', '40 hours', true, true, ARRAY['SAT','math','reading','writing'], ARRAY['high-school']),
('SAT Math - Complete Guide', 'Master all SAT math topics including algebra, geometry, data analysis, and advanced math', 'https://www.udemy.com/course/sat-math-complete/', 'SAT', 'intermediate', false, 'course', 'exam', 'Udemy', '20 hours', true, true, ARRAY['math','algebra','geometry','data analysis'], ARRAY['high-school']),
('SAT Reading & Writing Strategies', 'Evidence-based reading and writing strategies for high scores', 'https://www.magoosh.com/sat/', 'SAT', 'intermediate', false, 'course', 'exam', 'Magoosh', '15 hours', true, false, ARRAY['reading comprehension','grammar','writing'], ARRAY['high-school']),
('SAT Official Practice Tests', '8 full-length official SAT practice tests with answer explanations', 'https://satsuite.collegeboard.org/sat/practice-preparation/practice-tests', 'SAT', 'intermediate', true, 'exam_prep', 'exam', 'College Board', '30 hours', true, true, ARRAY['practice tests','full-length','official'], ARRAY['high-school']),
('SAT Vocabulary Power Plus', 'Essential SAT vocabulary with roots, prefixes, and context-based learning', 'https://www.vocabulary.com/lists/sat', 'SAT', 'beginner', true, 'website', 'exam', 'Vocabulary.com', '20 hours', true, false, ARRAY['vocabulary','word roots','context clues'], ARRAY['high-school']),
('SAT 1500+ Score Strategy', 'Advanced strategies for top scorers targeting 1500+ on the digital SAT', 'https://www.prepscholar.com/sat/s/1500/', 'SAT', 'advanced', false, 'course', 'exam', 'PrepScholar', '25 hours', true, false, ARRAY['high score','strategy','digital SAT'], ARRAY['high-school']),
('SAT Grammar Rules Complete Guide', 'All grammar and punctuation rules tested on the SAT with practice questions', 'https://www.udemy.com/course/sat-grammar/', 'SAT', 'beginner', false, 'course', 'exam', 'Udemy', '8 hours', true, false, ARRAY['grammar','punctuation','sentence structure'], ARRAY['high-school']),
('Digital SAT Bluebook Practice', 'Practice on the official Bluebook app for the digital SAT experience', 'https://bluebook.collegeboard.org/', 'SAT', 'intermediate', true, 'exam_prep', 'exam', 'College Board', '15 hours', true, false, ARRAY['digital SAT','Bluebook','adaptive testing'], ARRAY['high-school']),
('SAT Math Problem Solving Techniques', 'Learn time-saving techniques and shortcuts for SAT math problems', 'https://www.udemy.com/course/sat-math-tricks/', 'SAT', 'intermediate', false, 'course', 'exam', 'Udemy', '10 hours', true, false, ARRAY['math shortcuts','problem solving','time management'], ARRAY['high-school']),
('SAT Essay Writing Guide', 'Structure and style guide for the optional SAT essay with sample responses', 'https://www.prepscholar.com/sat/s/essay', 'SAT', 'intermediate', true, 'blog', 'exam', 'PrepScholar', '8 hours', true, false, ARRAY['essay writing','analysis','persuasion'], ARRAY['high-school']),
('Princeton Review SAT Prep', 'Comprehensive SAT prep course with video lessons, drills, and practice tests', 'https://www.princetonreview.com/college/sat-test-prep', 'SAT', 'intermediate', false, 'course', 'exam', 'Princeton Review', '40 hours', true, false, ARRAY['comprehensive prep','drills','review'], ARRAY['high-school']),
('SAT Subject-wise Analysis', 'Detailed topic-wise analysis and weightage guide for strategic SAT preparation', 'https://www.collegeboard.org/sat-subject-tests', 'SAT', 'beginner', true, 'website', 'exam', 'College Board', '5 hours', true, false, ARRAY['topic analysis','weightage','planning'], ARRAY['high-school']),

-- ==================== EXAM: GMAT (12 new) ====================
('GMAT Official Guide 2025', 'Official GMAC guide with 1000+ practice questions from past GMAT exams', 'https://www.mba.com/exams/gmat-exam/prepare', 'GMAT', 'intermediate', false, 'book', 'exam', 'GMAC', '80 hours', true, true, ARRAY['GMAT','quantitative','verbal','integrated reasoning'], ARRAY['bachelors']),
('GMAT Quantitative - Complete Math', 'Master data sufficiency, problem solving, arithmetic, algebra, and geometry', 'https://www.magoosh.com/gmat/', 'GMAT', 'intermediate', false, 'course', 'exam', 'Magoosh', '30 hours', true, true, ARRAY['quantitative','data sufficiency','problem solving'], ARRAY['bachelors']),
('GMAT Verbal - Critical Reasoning', 'Master GMAT critical reasoning with argument structures, assumptions, and weakening/strengthening', 'https://www.udemy.com/course/gmat-critical-reasoning/', 'GMAT', 'intermediate', false, 'course', 'exam', 'Udemy', '15 hours', true, false, ARRAY['critical reasoning','arguments','logical thinking'], ARRAY['bachelors']),
('GMAT Sentence Correction Bible', 'Comprehensive guide to GMAT sentence correction covering grammar, meaning, and concision', 'https://www.manhattanprep.com/gmat/', 'GMAT', 'intermediate', false, 'book', 'exam', 'Manhattan Prep', '25 hours', true, false, ARRAY['sentence correction','grammar','concision'], ARRAY['bachelors']),
('GMAT Focus Edition Prep', 'Updated preparation for the new GMAT Focus Edition format with adaptive practice', 'https://www.mba.com/exams/gmat-focus-edition', 'GMAT', 'intermediate', true, 'exam_prep', 'exam', 'GMAC', '40 hours', true, true, ARRAY['GMAT Focus','adaptive','new format'], ARRAY['bachelors']),
('GMAT Integrated Reasoning Guide', 'Master multi-source reasoning, table analysis, graphics interpretation, and two-part analysis', 'https://www.udemy.com/course/gmat-integrated-reasoning/', 'GMAT', 'intermediate', false, 'course', 'exam', 'Udemy', '10 hours', true, false, ARRAY['integrated reasoning','data interpretation','multi-source'], ARRAY['bachelors']),
('GMAT 700+ Score Strategy', 'Proven strategies for scoring 700+ including study plans, timing, and question prioritization', 'https://www.gmatclub.com/forum/700-strategy', 'GMAT', 'advanced', true, 'website', 'exam', 'GMAT Club', '20 hours', true, false, ARRAY['high score','strategy','time management'], ARRAY['bachelors']),
('GMAT AWA Essay Writing', 'Analysis of an argument essay - structure, templates, and high-scoring examples', 'https://www.udemy.com/course/gmat-awa/', 'GMAT', 'intermediate', false, 'course', 'exam', 'Udemy', '6 hours', true, false, ARRAY['AWA','essay','analytical writing'], ARRAY['bachelors']),
('GMAT Data Sufficiency Mastery', 'Advanced data sufficiency strategies and pattern recognition for GMAT quant', 'https://www.manhattanprep.com/gmat/store/gmat-strategy-guides/', 'GMAT', 'advanced', false, 'book', 'exam', 'Manhattan Prep', '20 hours', true, false, ARRAY['data sufficiency','quantitative','pattern recognition'], ARRAY['bachelors']),
('GMAT Reading Comprehension', 'Strategies for GMAT RC passages including main idea, inference, and detail questions', 'https://www.udemy.com/course/gmat-reading-comprehension/', 'GMAT', 'intermediate', false, 'course', 'exam', 'Udemy', '12 hours', true, false, ARRAY['reading comprehension','inference','main idea'], ARRAY['bachelors']),
('GMAT Mock Tests - Official', 'Official GMAT practice exams with exact scoring algorithm and performance tracking', 'https://www.mba.com/exams/gmat-exam/prepare/gmat-official-practice', 'GMAT', 'intermediate', true, 'exam_prep', 'exam', 'GMAC', '20 hours', true, false, ARRAY['mock tests','official','scoring'], ARRAY['bachelors']),
('GMAT Number Properties & Algebra', 'Deep dive into number theory, prime numbers, remainders, and algebraic equations', 'https://www.udemy.com/course/gmat-number-properties/', 'GMAT', 'intermediate', false, 'course', 'exam', 'Udemy', '14 hours', true, false, ARRAY['number properties','algebra','prime numbers'], ARRAY['bachelors']),

-- ==================== EXAM: LSAT (10 new) ====================
('LSAT Complete Prep - Khan Academy', 'Official LSAC partnership - free comprehensive LSAT preparation with practice', 'https://www.khanacademy.org/prep/lsat', 'LSAT', 'intermediate', true, 'course', 'exam', 'Khan Academy / LSAC', '60 hours', true, true, ARRAY['LSAT','logical reasoning','analytical reasoning','reading comprehension'], ARRAY['bachelors']),
('LSAT Logical Reasoning Bible', 'PowerScore''s definitive guide to LSAT logical reasoning with comprehensive strategies', 'https://www.powerscore.com/lsat/publications/', 'LSAT', 'intermediate', false, 'book', 'exam', 'PowerScore', '40 hours', true, true, ARRAY['logical reasoning','arguments','assumptions','flaws'], ARRAY['bachelors']),
('LSAT Logic Games Explained', 'Master analytical reasoning with grouping, ordering, and hybrid game types', 'https://7sage.com/logic-game-explanations/', 'LSAT', 'intermediate', true, 'video', 'exam', '7Sage', '30 hours', true, false, ARRAY['logic games','analytical reasoning','diagramming'], ARRAY['bachelors']),
('LSAT Reading Comprehension Strategies', 'Advanced RC strategies for law school passages including comparative reading', 'https://www.udemy.com/course/lsat-reading-comprehension/', 'LSAT', 'intermediate', false, 'course', 'exam', 'Udemy', '12 hours', true, false, ARRAY['reading comprehension','comparative reading','law passages'], ARRAY['bachelors']),
('LSAT 170+ Score Strategy', 'Elite strategies for scoring 170+ from top scorers and LSAT tutors', 'https://7sage.com/lsat-170/', 'LSAT', 'advanced', false, 'course', 'exam', '7Sage', '25 hours', true, false, ARRAY['high score','170+','elite strategy'], ARRAY['bachelors']),
('LSAT PrepTest Library', 'Access to 90+ official LSAT PrepTests with answer explanations', 'https://www.lsac.org/lsat/prep/official-lsat-preptests', 'LSAT', 'intermediate', false, 'exam_prep', 'exam', 'LSAC', '100 hours', true, true, ARRAY['PrepTests','official','practice'], ARRAY['bachelors']),
('LSAT Writing Section Guide', 'Complete guide to the LSAT writing section with sample prompts and responses', 'https://www.udemy.com/course/lsat-writing/', 'LSAT', 'beginner', false, 'course', 'exam', 'Udemy', '5 hours', true, false, ARRAY['writing','argument','decision-making'], ARRAY['bachelors']),
('LSAT Assumption & Flaw Questions', 'Master the most common LSAT logical reasoning question types', 'https://www.powerscore.com/lsat/help/', 'LSAT', 'intermediate', true, 'website', 'exam', 'PowerScore', '15 hours', true, false, ARRAY['assumptions','flaws','strengthen/weaken'], ARRAY['bachelors']),
('LSAT Digital Practice', 'Practice on the digital LSAT interface with timed sections and flagging', 'https://www.lsac.org/lsat/prep/preparing-digital-lsat', 'LSAT', 'intermediate', true, 'exam_prep', 'exam', 'LSAC', '20 hours', true, false, ARRAY['digital LSAT','interface','timed practice'], ARRAY['bachelors']),
('LSAT Conditional Reasoning', 'Deep dive into conditional logic, contrapositives, and chain reasoning', 'https://www.udemy.com/course/lsat-conditional-reasoning/', 'LSAT', 'advanced', false, 'course', 'exam', 'Udemy', '8 hours', true, false, ARRAY['conditional logic','contrapositives','chain reasoning'], ARRAY['bachelors']),

-- ==================== EXAM: MCAT (10 new) ====================
('MCAT Complete Prep - AAMC', 'Official AAMC MCAT preparation with practice questions and full-length tests', 'https://students-residents.aamc.org/prepare-mcat-exam/prepare-mcat-exam', 'MCAT', 'advanced', false, 'exam_prep', 'exam', 'AAMC', '80 hours', true, true, ARRAY['MCAT','biology','chemistry','physics','CARS'], ARRAY['bachelors']),
('MCAT Biology & Biochemistry', 'Comprehensive bio/biochem review for MCAT including molecular biology and metabolism', 'https://www.khanacademy.org/test-prep/mcat', 'MCAT', 'intermediate', true, 'course', 'exam', 'Khan Academy', '60 hours', true, true, ARRAY['biology','biochemistry','metabolism','molecular biology'], ARRAY['bachelors']),
('MCAT CARS Strategy Guide', 'Critical Analysis and Reasoning Skills - passage analysis and question strategies', 'https://www.udemy.com/course/mcat-cars-strategy/', 'MCAT', 'intermediate', false, 'course', 'exam', 'Udemy', '15 hours', true, false, ARRAY['CARS','critical analysis','reasoning','passage analysis'], ARRAY['bachelors']),
('MCAT Chemistry & Physics Review', 'General chemistry, organic chemistry, and physics review tailored for MCAT', 'https://www.kaplan.com/mcat/prep-course', 'MCAT', 'intermediate', false, 'course', 'exam', 'Kaplan', '100 hours', true, true, ARRAY['chemistry','physics','organic chemistry','general chemistry'], ARRAY['bachelors']),
('MCAT Psychology & Sociology', 'Behavioral sciences section prep covering psychology, sociology, and biology foundations', 'https://www.udemy.com/course/mcat-psychology-sociology/', 'MCAT', 'intermediate', false, 'course', 'exam', 'Udemy', '20 hours', true, false, ARRAY['psychology','sociology','behavioral sciences'], ARRAY['bachelors']),
('MCAT 520+ Score Strategy', 'Elite MCAT strategies from 520+ scorers with detailed study plans', 'https://www.reddit.com/r/Mcat/wiki/studyplan', 'MCAT', 'advanced', true, 'website', 'exam', 'Reddit r/Mcat', '10 hours', true, false, ARRAY['high score','study plan','strategy'], ARRAY['bachelors']),
('MCAT Anki Flashcard Decks', 'Comprehensive Anki decks for MCAT covering all subjects with spaced repetition', 'https://ankiweb.net/shared/decks/mcat', 'MCAT', 'intermediate', true, 'website', 'exam', 'AnkiWeb', '100 hours', true, false, ARRAY['flashcards','spaced repetition','review'], ARRAY['bachelors']),
('MCAT Full-Length Practice Tests', 'Realistic full-length MCAT practice exams with score prediction', 'https://www.aamc.org/students/applying/mcat/prepare/practice-exams', 'MCAT', 'intermediate', false, 'exam_prep', 'exam', 'AAMC', '40 hours', true, false, ARRAY['full-length tests','scoring','practice'], ARRAY['bachelors']),
('MCAT Organic Chemistry Mechanisms', 'Master organic chemistry reaction mechanisms essential for MCAT', 'https://www.udemy.com/course/mcat-organic-chemistry/', 'MCAT', 'advanced', false, 'course', 'exam', 'Udemy', '18 hours', true, false, ARRAY['organic chemistry','mechanisms','reactions','synthesis'], ARRAY['bachelors']),
('MCAT Amino Acids & Proteins', 'Complete guide to amino acids, protein structure, enzymology, and metabolism', 'https://www.khanacademy.org/test-prep/mcat/biomolecules', 'MCAT', 'intermediate', true, 'course', 'exam', 'Khan Academy', '12 hours', true, false, ARRAY['amino acids','proteins','enzymology','metabolism'], ARRAY['bachelors']);
