-- Normalize resources.domain / resources.subdomain to match the canonical
-- Category → Domain → Subdomain mapping in src/utils/categoryMapping.ts.
WITH mapping(category, domain, subdomain) AS (
  VALUES
    -- Technology
    ('Web Development','Technology','Web Development'),
    ('Full Stack Development','Technology','Web Development'),
    ('Mobile Development','Technology','Mobile Development'),
    ('JavaScript','Technology','JavaScript'),
    ('Python','Technology','Python'),
    ('Programming','Technology','Programming'),
    ('Development','Technology','Programming'),
    ('Computer Applications','Technology','Computer Applications'),
    ('Computer Science','Technology','Computer Science'),
    ('DSA','Technology','DSA'),
    ('System Design','Technology','System Design'),
    ('Game Development','Technology','Game Development'),
    ('Blockchain','Technology','Blockchain'),
    ('Cloud Computing','Technology','Cloud Computing'),
    ('AWS','Technology','Cloud Computing'),
    ('DevOps','Technology','DevOps'),
    ('Networking','Technology','Networking'),
    ('Cybersecurity','Technology','Cybersecurity'),
    ('Database','Technology','Database'),
    ('General','Technology','General'),
    -- AI & Data
    ('Machine Learning','AI & Data','Machine Learning'),
    ('AI/ML','AI & Data','AI/ML'),
    ('Artificial Intelligence','AI & Data','Artificial Intelligence'),
    ('Data Science','AI & Data','Data Science'),
    -- Business & Finance
    ('Business & Management','Business & Finance','Management'),
    ('Business Administration','Business & Finance','Management'),
    ('Management','Business & Finance','Management'),
    ('Project Management','Business & Finance','Project Management'),
    ('Business','Business & Finance','Business'),
    ('Supply Chain & Procurement','Business & Finance','Operations'),
    ('Event Management','Business & Finance','Operations'),
    ('Human Resources','Business & Finance','Human Resources'),
    ('Marketing','Business & Finance','Marketing'),
    ('Digital Marketing','Business & Finance','Digital Marketing'),
    ('Content Marketing','Business & Finance','Marketing'),
    ('Social Media Marketing','Business & Finance','Marketing'),
    ('Public Relations & Communications','Business & Finance','Marketing'),
    ('Communication','Business & Finance','Communication'),
    ('Finance','Business & Finance','Finance'),
    ('Finance & Accounting','Business & Finance','Finance'),
    ('Accounting & Finance','Business & Finance','Finance'),
    ('Accounting','Business & Finance','Finance'),
    ('Investment','Business & Finance','Finance'),
    ('Finance & Investment','Business & Finance','Finance'),
    ('Financial Planning','Business & Finance','Finance'),
    ('Economics','Business & Finance','Economics'),
    -- Arts & Design
    ('Design','Arts & Design','Design'),
    ('UI/UX Design','Arts & Design','UI/UX Design'),
    ('Graphic Design','Arts & Design','Graphic Design'),
    ('Interior Design','Arts & Design','Design'),
    ('Fashion Design','Arts & Design','Fashion'),
    ('Fashion Styling','Arts & Design','Fashion'),
    ('Architecture','Arts & Design','Architecture'),
    ('Fine Arts','Arts & Design','Arts'),
    ('Arts & Painting','Arts & Design','Arts'),
    ('Music','Arts & Design','Music'),
    ('Performing Arts','Arts & Design','Performing Arts'),
    ('Dance','Arts & Design','Performing Arts'),
    ('Film & Cinema','Arts & Design','Film & Video'),
    ('Film & Video','Arts & Design','Film & Video'),
    ('Animation','Arts & Design','Animation'),
    ('Animation & VFX','Arts & Design','Animation'),
    ('Photography','Arts & Design','Photography'),
    ('Creative Writing','Arts & Design','Writing'),
    ('Culinary Arts','Arts & Design','Culinary Arts'),
    -- Humanities & Social Sciences
    ('Psychology','Humanities & Social Sciences','Psychology'),
    ('Journalism & Media','Humanities & Social Sciences','Journalism'),
    ('Journalism','Humanities & Social Sciences','Journalism'),
    ('International Relations','Humanities & Social Sciences','Political Science'),
    ('Political Science','Humanities & Social Sciences','Political Science'),
    ('Social Work','Humanities & Social Sciences','Sociology'),
    ('Museum & Heritage Studies','Humanities & Social Sciences','History'),
    ('Philosophy','Humanities & Social Sciences','Philosophy'),
    ('Law','Humanities & Social Sciences','Law'),
    ('Law & Legal Studies','Humanities & Social Sciences','Law'),
    ('Education','Humanities & Social Sciences','Education'),
    ('Education & Teaching','Humanities & Social Sciences','Education'),
    -- Health & Lifestyle
    ('Health & Fitness','Health & Lifestyle','Health & Fitness'),
    ('Nutrition & Health','Health & Lifestyle','Nutrition'),
    ('Hospitality & Food & Beverage','Health & Lifestyle','Food & Beverage'),
    -- General Studies
    ('Environmental Science','General Studies','Environmental Science'),
    -- Exam Prep
    ('GRE','Exam Prep','GRE'),
    ('Exam Prep - GRE','Exam Prep','GRE'),
    ('CAT','Exam Prep','CAT'),
    ('Exam Prep - CAT','Exam Prep','CAT'),
    ('GATE','Exam Prep','GATE'),
    ('Exam Prep - GATE','Exam Prep','GATE'),
    ('UPSC','Exam Prep','UPSC'),
    ('Exam Prep - UPSC','Exam Prep','UPSC'),
    ('NEET','Exam Prep','NEET'),
    ('Exam Prep - NEET','Exam Prep','NEET'),
    ('JEE','Exam Prep','JEE'),
    ('Exam Prep - JEE','Exam Prep','JEE'),
    ('TOEFL','Exam Prep','TOEFL'),
    ('IELTS','Exam Prep','IELTS'),
    ('SAT','Exam Prep','SAT'),
    ('LSAT','Exam Prep','LSAT'),
    ('GMAT','Exam Prep','GMAT'),
    ('MCAT','Exam Prep','MCAT'),
    ('CompTIA','Exam Prep','CompTIA')
)
UPDATE public.resources r
SET domain = m.domain,
    subdomain = m.subdomain
FROM mapping m
WHERE r.category = m.category
  AND (r.domain IS DISTINCT FROM m.domain OR r.subdomain IS DISTINCT FROM m.subdomain);