
-- SEED POSTS with valid categories only
INSERT INTO posts (user_id, title, content, category, tags) VALUES
((SELECT user_id FROM profiles LIMIT 1), 'Must Watch: Complete Docker Tutorial for Beginners 🐳', '{"type":"post","blocks":[{"type":"paragraph","content":"This comprehensive Docker tutorial covers everything from basics to advanced container orchestration."},{"type":"video","videoUrl":"https://www.youtube.com/watch?v=fqMOX6JJhGo"}]}', 'Technology', ARRAY['Docker', 'DevOps', 'Tutorial']),
((SELECT user_id FROM profiles LIMIT 1), 'JavaScript ES2024 Features You Need to Know 🚀', '{"type":"post","blocks":[{"type":"paragraph","content":"JavaScript keeps evolving! Here are the most exciting ES2024 features."},{"type":"video","videoUrl":"https://www.youtube.com/watch?v=TuDCxQZH00o"}]}', 'Technology', ARRAY['JavaScript', 'Programming']),
((SELECT user_id FROM profiles LIMIT 1), 'How I Landed a 25 LPA Job at Google 💼', '{"type":"post","blocks":[{"type":"paragraph","content":"After 2 years of preparation, I cracked Google! Complete roadmap inside."}]}', 'Career', ARRAY['Google', 'FAANG', 'Interview']),
((SELECT user_id FROM profiles LIMIT 1), 'Free Courses That Changed My Career 📚', '{"type":"post","blocks":[{"type":"paragraph","content":"These FREE courses helped me transition to software engineering in 18 months."}]}', 'Resources', ARRAY['Free Courses', 'Learning']),
((SELECT user_id FROM profiles LIMIT 1), 'GATE 2025 Preparation Strategy - AIR Under 100 🎯', '{"type":"post","blocks":[{"type":"paragraph","content":"Secured AIR 87 in GATE CSE. Complete 8-month strategy inside."}]}', 'Exam Prep', ARRAY['GATE', 'Engineering']),
((SELECT user_id FROM profiles LIMIT 1), 'Build Your First AI App with ChatGPT API 🤖', '{"type":"post","blocks":[{"type":"paragraph","content":"Complete tutorial on building AI apps."},{"type":"video","videoUrl":"https://www.youtube.com/watch?v=uRQH2CFvedY"}]}', 'Technology', ARRAY['AI', 'ChatGPT']),
((SELECT user_id FROM profiles LIMIT 1), 'Top 10 AI Tools Every Developer Should Use 🛠️', '{"type":"post","blocks":[{"type":"paragraph","content":"AI tools that 10x my productivity daily."}]}', 'News', ARRAY['AI', 'Tools', 'Productivity']),
((SELECT user_id FROM profiles LIMIT 1), 'Is a CS Degree Still Worth It? 🎓', '{"type":"post","blocks":[{"type":"paragraph","content":"Controversial take on degrees vs self-taught in 2024."}]}', 'Discussion', ARRAY['CS Degree', 'Career']),
((SELECT user_id FROM profiles LIMIT 1), 'Python for Data Science: Complete Guide 🐍', '{"type":"post","blocks":[{"type":"paragraph","content":"Complete beginner roadmap for data science."},{"type":"video","videoUrl":"https://www.youtube.com/watch?v=_uQrJ0TkZlc"}]}', 'Technology', ARRAY['Python', 'Data Science']),
((SELECT user_id FROM profiles LIMIT 1), 'Complete Cybersecurity Roadmap 2024 🔐', '{"type":"post","blocks":[{"type":"paragraph","content":"How to break into cybersecurity."},{"type":"video","videoUrl":"https://www.youtube.com/watch?v=3Kq1MIfTWCE"}]}', 'Technology', ARRAY['Cybersecurity', 'Career']),
((SELECT user_id FROM profiles LIMIT 1), 'Remote Work Setup That Boosted Productivity 🏠', '{"type":"post","blocks":[{"type":"paragraph","content":"My optimized WFH setup after 4 years."}]}', 'Career', ARRAY['Remote Work', 'Productivity']),
((SELECT user_id FROM profiles LIMIT 1), 'Built a SaaS in 30 Days 🚀', '{"type":"post","blocks":[{"type":"paragraph","content":"Complete journey building and launching a SaaS product."}]}', 'Projects', ARRAY['SaaS', 'Full Stack']),
((SELECT user_id FROM profiles LIMIT 1), 'CAT 2024: 60 to 99.5 Percentile Journey 📈', '{"type":"post","blocks":[{"type":"paragraph","content":"Complete CAT preparation strategy that worked."}]}', 'Exam Prep', ARRAY['CAT', 'MBA']),
((SELECT user_id FROM profiles LIMIT 1), 'Best React Patterns in 2024 ⚛️', '{"type":"post","blocks":[{"type":"paragraph","content":"Modern React patterns every developer should know."}]}', 'Programming', ARRAY['React', 'JavaScript']),
((SELECT user_id FROM profiles LIMIT 1), 'AWS Solutions Architect Tips 🏆', '{"type":"post","blocks":[{"type":"paragraph","content":"How I passed AWS SAA on first attempt."}]}', 'Technology', ARRAY['AWS', 'Cloud', 'Certification']);
