UPDATE resources AS r
SET 
  domain = m.domain,
  subdomain = m.subdomain
FROM (
  VALUES 
    ('Web Development', 'Technology', 'Web Development'),
    ('Full Stack Development', 'Technology', 'Web Development'),
    ('Mobile Development', 'Technology', 'Mobile Development'),
    ('JavaScript', 'Technology', 'Programming'),
    ('Python', 'Technology', 'Programming'),
    ('Programming', 'Technology', 'Programming'),
    ('Development', 'Technology', 'Programming'),
    ('Computer Applications', 'Technology', 'Computer Science'),
    ('Computer Science', 'Technology', 'Computer Science'),
    ('DSA', 'Technology', 'Computer Science'),
    ('System Design', 'Technology', 'Computer Science'),
    ('Game Development', 'Technology', 'Game Development'),
    ('Blockchain', 'Technology', 'Blockchain'),
    ('Cloud Computing', 'Technology', 'Cloud & Infrastructure'),
    ('AWS', 'Technology', 'Cloud & Infrastructure'),
    ('DevOps', 'Technology', 'Cloud & Infrastructure'),
    ('Networking', 'Technology', 'Cloud & Infrastructure'),
    ('Cybersecurity', 'Technology', 'Cybersecurity'),
    ('Database', 'Technology', 'Database'),
    ('Machine Learning', 'AI & Data', 'Machine Learning'),
    ('AI/ML', 'AI & Data', 'Machine Learning'),
    ('Artificial Intelligence', 'AI & Data', 'Artificial Intelligence'),
    ('Data Science', 'AI & Data', 'Data Science'),
    ('Business & Management', 'Business & Finance', 'Management'),
    ('Business Administration', 'Business & Finance', 'Management'),
    ('Management', 'Business & Finance', 'Management'),
    ('Project Management', 'Business & Finance', 'Management'),
    ('Business', 'Business & Finance', 'Business'),
    ('Supply Chain & Procurement', 'Business & Finance', 'Operations'),
    ('Event Management', 'Business & Finance', 'Operations'),
    ('Human Resources', 'Business & Finance', 'Human Resources'),
    ('Marketing', 'Business & Finance', 'Marketing'),
    ('Digital Marketing', 'Business & Finance', 'Marketing'),
    ('Content Marketing', 'Business & Finance', 'Marketing'),
    ('Social Media Marketing', 'Business & Finance', 'Marketing'),
    ('Public Relations & Communications', 'Business & Finance', 'Marketing'),
    ('Communication', 'Business & Finance', 'Communication'),
    ('Finance', 'Business & Finance', 'Finance'),
    ('Finance & Accounting', 'Business & Finance', 'Finance'),
    ('Accounting & Finance', 'Business & Finance', 'Finance'),
    ('Accounting', 'Business & Finance', 'Finance'),
    ('Investment', 'Business & Finance', 'Finance'),
    ('Finance & Investment', 'Business & Finance', 'Finance'),
    ('Financial Planning', 'Business & Finance', 'Finance'),
    ('Economics', 'Business & Finance', 'Economics'),
    ('Design', 'Design & Arts', 'Design'),
    ('UI/UX Design', 'Design & Arts', 'Design'),
    ('Graphic Design', 'Design & Arts', 'Design'),
    ('Interior Design', 'Design & Arts', 'Design'),
    ('Fashion Design', 'Design & Arts', 'Fashion'),
    ('Fashion Styling', 'Design & Arts', 'Fashion'),
    ('Architecture', 'Design & Arts', 'Architecture'),
    ('Fine Arts', 'Design & Arts', 'Arts'),
    ('Arts & Painting', 'Design & Arts', 'Arts'),
    ('Music', 'Design & Arts', 'Music'),
    ('Performing Arts', 'Design & Arts', 'Performing Arts'),
    ('Dance', 'Design & Arts', 'Performing Arts'),
    ('Film & Cinema', 'Design & Arts', 'Film & Animation'),
    ('Film & Video', 'Design & Arts', 'Film & Animation'),
    ('Animation', 'Design & Arts', 'Film & Animation'),
    ('Animation & VFX', 'Design & Arts', 'Film & Animation'),
    ('Photography', 'Design & Arts', 'Photography'),
    ('Psychology', 'Humanities & Social Sciences', 'Psychology'),
    ('Journalism & Media', 'Humanities & Social Sciences', 'Journalism'),
    ('Journalism', 'Humanities & Social Sciences', 'Journalism'),
    ('Creative Writing', 'Humanities & Social Sciences', 'Writing'),
    ('International Relations', 'Humanities & Social Sciences', 'Political Science'),
    ('Political Science', 'Humanities & Social Sciences', 'Political Science'),
    ('Social Work', 'Humanities & Social Sciences', 'Sociology'),
    ('Museum & Heritage Studies', 'Humanities & Social Sciences', 'History'),
    ('Philosophy', 'Humanities & Social Sciences', 'Philosophy'),
    ('Law', 'Humanities & Social Sciences', 'Law'),
    ('Law & Legal Studies', 'Humanities & Social Sciences', 'Law'),
    ('Education', 'Humanities & Social Sciences', 'Education'),
    ('Education & Teaching', 'Humanities & Social Sciences', 'Education'),
    ('Health & Fitness', 'Health & Lifestyle', 'Health'),
    ('Nutrition & Health', 'Health & Lifestyle', 'Nutrition'),
    ('Culinary Arts', 'Health & Lifestyle', 'Food & Beverage'),
    ('Hospitality & Food & Beverage', 'Health & Lifestyle', 'Food & Beverage'),
    ('Environmental Science', 'Health & Lifestyle', 'Environment'),
    ('GRE', 'Academics & Exams', 'Exam Prep'),
    ('Exam Prep - GRE', 'Academics & Exams', 'Exam Prep'),
    ('CAT', 'Academics & Exams', 'Exam Prep'),
    ('Exam Prep - CAT', 'Academics & Exams', 'Exam Prep'),
    ('GATE', 'Academics & Exams', 'Exam Prep'),
    ('Exam Prep - GATE', 'Academics & Exams', 'Exam Prep'),
    ('UPSC', 'Academics & Exams', 'Exam Prep'),
    ('Exam Prep - UPSC', 'Academics & Exams', 'Exam Prep'),
    ('NEET', 'Academics & Exams', 'Exam Prep'),
    ('Exam Prep - NEET', 'Academics & Exams', 'Exam Prep'),
    ('JEE', 'Academics & Exams', 'Exam Prep'),
    ('Exam Prep - JEE', 'Academics & Exams', 'Exam Prep'),
    ('TOEFL', 'Academics & Exams', 'Exam Prep'),
    ('IELTS', 'Academics & Exams', 'Exam Prep'),
    ('SAT', 'Academics & Exams', 'Exam Prep'),
    ('LSAT', 'Academics & Exams', 'Exam Prep'),
    ('GMAT', 'Academics & Exams', 'Exam Prep'),
    ('MCAT', 'Academics & Exams', 'Exam Prep'),
    ('CompTIA', 'Academics & Exams', 'Exam Prep'),
    ('General', 'General', 'General')
) AS m(category, domain, subdomain)
WHERE r.category = m.category AND (r.domain IS NULL OR r.subdomain IS NULL);

ALTER TABLE resources
ALTER COLUMN domain SET NOT NULL;

ALTER TABLE resources
ALTER COLUMN subdomain SET NOT NULL;
